QMapControl: CirclePoint Class Reference
CirclePoint Class Reference
Draws a circle into the map.
#include <circlepoint.h>
Public Types
enum Alignment {
TopLeft, TopRight, TopMiddle, BottomLeft,
BottomRight, BottomMiddle, Middle
}
sets where the point should be aligned
Signals
void geometryClicked (Geometry *geometry, QPoint point)
This signal is emitted when a Geometry is clicked.
void positionChanged (Geometry *geom)
A Geometry emits this signal, when its position gets changed.
Public Member Functions
virtual QRectF boundingBox ()
returns the bounding box of the point
CirclePoint (qreal x, qreal y, QString name=QString(), Alignment alignment=Middle, QPen *pen=0)
CirclePoint (qreal x, qreal y, int radius=10, QString name=QString(), Alignment alignment=Middle, QPen *pen=0)
QPointF coordinate () const
returns the coordinate of the point
bool Equals (Geometry *geom)
bool isVisible () const
returns true if this Geometry is visible
qreal latitude () const
returns the latitude of the point
qreal longitude () const
returns the longitude of the point
QString name () const
returns the name of this Geometry
Geometry * parentGeometry () const
returns the parent Geometry of this Geometry
QPen * pen () const
returns the QPen which is used on drawing
QPixmap pixmap ()
returns the pixmap of the point
void setBaselevel (int zoomlevel)
Sets the zoom level on which the points pixmap gets displayed on full size.
void setMaxsize (QSize maxsize)
sets a maximal size for the pixmap
void setMinsize (QSize minsize)
sets a minimal size for the pixmap
void setName (QString name)
sets the name of the geometry
virtual void setPen (QPen *pen)
sets the QPen which is used for drawing the circle
QString toString ()
returns a String representation of this Geometry
QWidget * widget ()
returns the widget of the point
Protected Member Functions
virtual bool Touches (Point *click, const MapAdapter *mapadapter)
returns true if the given Point touches this Point
Detailed Description
Draws a circle into the map.
This is a conveniece class for Point. It configures the pixmap of a Point to draw a circle. A QPen could be used to change the color or line-width of the circle
Author
Kai Winter kaiwi.nosp@m.nter.nosp@m.@gmx..nosp@m.de
Member Enumeration Documentation
enum Alignment inherited
sets where the point should be aligned
Enumerator
TopLeft
Align on TopLeft
TopRight
Align on TopRight
TopMiddle
Align on TopLeft
BottomLeft
Align on BottomLeft
BottomRight
Align on BottomRight
BottomMiddle
Align on BottomMiddle
Middle
Align on Middle
Constructor & Destructor Documentation
CirclePoint (qreal x, qreal y, QString name = QString(), Alignment alignment = Middle, QPen * pen = 0)
Parameters
x longitude
y latitude
name name of the circle point
alignment alignment (Middle or TopLeft)
pen QPen for drawing
References Geometry::pen().
CirclePoint (qreal x, qreal y, int radius = 10, QString name = QString(), Alignment alignment = Middle, QPen * pen = 0)
Parameters
x longitude
y latitude
radius the radius of the circle
name name of the circle point
alignment alignment (Middle or TopLeft)
pen QPen for drawing
References Geometry::pen().
Member Function Documentation
QRectF boundingBox () virtual inherited
returns the bounding box of the point
The Bounding contains the coordinate of the point and its size. The size is set, if the point contains a pixmap or a widget
Returns
the bounding box of the point
Implements Geometry.
References Point::latitude(), and Point::longitude().
QPointF coordinate () const inherited
returns the coordinate of the point
The x component of the returned QPointF is the longitude value, the y component the latitude
Returns
the coordinate of a point
Referenced by MapControl::setView(), and Point::Touches().
bool Equals (Geometry * geom) inherited
returns true if the given Geometry is equal to this Geometry not implemented yet!
Parameters
geom The Geometry to be tested
Returns
true if the given Geometry is equal to this
void geometryClicked (Geometry * geometry, QPoint point) signal inherited
This signal is emitted when a Geometry is clicked.
A Geometry is clickable, if the containing layer is clickable. The objects emits a signal if it gets clicked
Parameters
geometry The clicked Geometry
point -unused-
Referenced by Point::Touches().
bool isVisible () const inherited
returns true if this Geometry is visible
Returns
true if this Geometry is visible
Referenced by Point::Touches().
qreal latitude () const inherited
returns the latitude of the point
Returns
the latitude of the point
Referenced by LineString::boundingBox(), and Point::boundingBox().
qreal longitude () const inherited
returns the longitude of the point
Returns
the longitude of the point
Referenced by LineString::boundingBox(), and Point::boundingBox().
QString name () const inherited
returns the name of this Geometry
Returns
the name of this Geometry
Referenced by Geometry::setName().
Geometry * parentGeometry () const inherited
returns the parent Geometry of this Geometry
A LineString is a composition of many Points. This methods returns the parent (the LineString) of a Point
Returns
the parent Geometry of this Geometry
QPen * pen () const inherited
returns the QPen which is used on drawing
The pen is set depending on the Geometry. A CirclePoint for example takes one with the constructor.
Returns
the QPen which is used for drawing
Referenced by ArrowPoint::ArrowPoint(), CirclePoint::CirclePoint(), LineString::LineString(), ArrowPoint::setPen(), and CirclePoint::setPen().
QPixmap pixmap () inherited
returns the pixmap of the point
Returns
the pixmap of the point
Referenced by FixedImageOverlay::FixedImageOverlay(), and ImagePoint::ImagePoint().
void positionChanged (Geometry * geom) signal inherited
A Geometry emits this signal, when its position gets changed.
Parameters
geom the Geometry
void setBaselevel (int zoomlevel) inherited
Sets the zoom level on which the points pixmap gets displayed on full size.
Use this method to set a zoom level on which the pixmap gets displayed with its real size. On zoomlevels below it will be displayed smaller, and on zoom levels thereover it will be displayed larger
See also
setMinsize, setMaxsize
Parameters
zoomlevel the zoomlevel on which the point will be displayed on full size
void setMaxsize (QSize maxsize) inherited
sets a maximal size for the pixmap
When the point´s pixmap should change its size on zooming, this method sets the maximal size.
See also
setBaselevel
Parameters
maxsize the maximal size which the pixmap should have
void setMinsize (QSize minsize) inherited
sets a minimal size for the pixmap
When the point's pixmap should change its size on zooming, this method sets the minimal size.
See also
setBaselevel
Parameters
minsize the minimal size which the pixmap should have
void setName (QString name) inherited
sets the name of the geometry
Parameters
name the new name of the geometry
References Geometry::name().
void setPen (QPen * pen) virtual
sets the QPen which is used for drawing the circle
A QPen can be used to modify the look of the drawn circle
Parameters
pen the QPen which should be used for drawing
See also
http://doc.trolltech.com/4.3/qpen.html
Reimplemented from Geometry.
References Geometry::pen().
QString toString () inherited
returns a String representation of this Geometry
not implemented yet!
Returns
a String representation of this Geometry
bool Touches (Point * click, const MapAdapter * mapadapter) protected virtual inherited
returns true if the given Point touches this Point
The collision detection checks for the bounding rectangulars.
Parameters
geom the other point which should be tested on collision
mapadapter the mapadapter which is used for calculations
Returns
Implements Geometry.
References Point::coordinate(), MapAdapter::coordinateToDisplay(), Geometry::geometryClicked(), and Geometry::isVisible().
QWidget * widget () inherited
returns the widget of the point
Returns
the widget of the point
The documentation for this class was generated from the following files:
circlepoint.h
circlepoint.cpp