QMapControl: MapAdapter Class Reference
MapAdapter Class Reference abstract
Used to fit map servers into QMapControl.
#include <mapadapter.h>
Public Member Functions
virtual void changeHostAddress (const QString qHost, const QString qServerPath=QString())
change or update server host address post init
virtual QPoint coordinateToDisplay (const QPointF &coordinate) const =0
translates a world coordinate to display coordinate
int currentZoom () const
returns the current zoom
virtual QPointF displayToCoordinate (const QPoint &point) const =0
translates display coordinate to world coordinate
QString host () const
returns the host of this MapAdapter
int maxZoom () const
returns the max zoom value
int minZoom () const
returns the min zoom value
virtual QString serverPath () const
returns the server path part of this MapAdapter
int tilesize () const
returns the size of the tiles
Detailed Description
Used to fit map servers into QMapControl.
MapAdapters are needed to convert between world- and display coordinates. This calculations depend on the used map projection. There are two ready-made MapAdapters:
TileMapAdapter, which is ready to use for OpenStreetMap or Google (Mercator projection)
WMSMapAdapter, which could be used for the most WMS-Server (some servers show errors, because of image ratio)
MapAdapters are also needed to form the HTTP-Queries to load the map tiles. The maps from WMS Servers are also divided into tiles, because those can be better cached.
See also
TileMapAdapter,
WMSMapAdapter
Author
Kai Winter kaiwi.nosp@m.nter.nosp@m.@gmx..nosp@m.de
Member Function Documentation
void changeHostAddress (const QString qHost, const QString qServerPath = QString()) virtual
change or update server host address post init
Parameters
host the host address
serverPath the server path
Reimplemented in WMSMapAdapter.
Referenced by WMSMapAdapter::changeHostAddress().
virtual QPoint coordinateToDisplay (const QPointF & coordinate) const pure virtual
translates a world coordinate to display coordinate
The calculations also needs the current zoom. The current zoom is managed by the MapAdapter, so this is no problem. To divide model from view the current zoom should be moved to the layers.
Parameters
coordinate the world coordinate
Returns
the display coordinate (in widget coordinates)
Implemented in TileMapAdapter, EmptyMapAdapter, and WMSMapAdapter.
Referenced by Point::Touches().
int currentZoom () const
returns the current zoom
Returns
the current zoom
virtual QPointF displayToCoordinate (const QPoint & point) const pure virtual
translates display coordinate to world coordinate
The calculations also needs the current zoom. The current zoom is managed by the MapAdapter, so this is no problem. To divide model from view the current zoom should be moved to the layers.
Parameters
point the display coordinate
Returns
the world coordinate
Implemented in TileMapAdapter, EmptyMapAdapter, and WMSMapAdapter.
QString host () const
returns the host of this MapAdapter
Returns
the host of this MapAdapter
int maxZoom () const
returns the max zoom value
Returns
the max zoom value
int minZoom () const
returns the min zoom value
Returns
the min zoom value
QString serverPath () const virtual
returns the server path part of this MapAdapter
Returns
the serverpath of this MapAdapter
Reimplemented in WMSMapAdapter.
Referenced by WMSMapAdapter::serverPath().
int tilesize () const
returns the size of the tiles
Returns
the size of the tiles
Referenced by WMSMapAdapter::changeHostAddress().
The documentation for this class was generated from the following files:
mapadapter.h
mapadapter.cpp