QMapControl: GoogleMapAdapter Class Reference
GoogleMapAdapter Class Reference
MapAdapter for Google.
#include <googlemapadapter.h>
Public Member Functions
virtual void changeHostAddress (const QString qHost, const QString qServerPath=QString())
change or update server host address post init
virtual QPoint coordinateToDisplay (const QPointF &) const
translates a world coordinate to display coordinate
int currentZoom () const
returns the current zoom
virtual QPointF displayToCoordinate (const QPoint &) const
translates display coordinate to world coordinate
GoogleMapAdapter (googleLayerType qLayerType=maps)
constructor
QString host () const
returns the host of this MapAdapter
int maxZoom () const
returns the max zoom value
int minZoom () const
returns the min zoom value
virtual QString serverPath () const
returns the server path part of this MapAdapter
int tilesize () const
returns the size of the tiles
Detailed Description
MapAdapter for Google.
This is a conveniece class, which extends and configures a TileMapAdapter
Author
Kai Winter kaiwi.nosp@m.nter.nosp@m.@gmx..nosp@m.de
Constructor & Destructor Documentation
GoogleMapAdapter (googleLayerType qLayerType = maps)
constructor
This construct a Google Adapter
Member Function Documentation
void changeHostAddress (const QString qHost, const QString qServerPath = QString()) virtual inherited
change or update server host address post init
Parameters
host the host address
serverPath the server path
Reimplemented in WMSMapAdapter.
Referenced by WMSMapAdapter::changeHostAddress().
QPoint coordinateToDisplay (const QPointF & coordinate) const virtual inherited
translates a world coordinate to display coordinate
The calculations also needs the current zoom. The current zoom is managed by the MapAdapter, so this is no problem. To divide model from view the current zoom should be moved to the layers.
Parameters
coordinate the world coordinate
Returns
the display coordinate (in widget coordinates)
Implements MapAdapter.
int currentZoom () const inherited
returns the current zoom
Returns
the current zoom
QPointF displayToCoordinate (const QPoint & point) const virtual inherited
translates display coordinate to world coordinate
The calculations also needs the current zoom. The current zoom is managed by the MapAdapter, so this is no problem. To divide model from view the current zoom should be moved to the layers.
Parameters
point the display coordinate
Returns
the world coordinate
Implements MapAdapter.
QString host () const inherited
returns the host of this MapAdapter
Returns
the host of this MapAdapter
int maxZoom () const inherited
returns the max zoom value
Returns
the max zoom value
int minZoom () const inherited
returns the min zoom value
Returns
the min zoom value
QString serverPath () const virtual inherited
returns the server path part of this MapAdapter
Returns
the serverpath of this MapAdapter
Reimplemented in WMSMapAdapter.
Referenced by WMSMapAdapter::serverPath().
int tilesize () const inherited
returns the size of the tiles
Returns
the size of the tiles
Referenced by WMSMapAdapter::changeHostAddress().
The documentation for this class was generated from the following files:
googlemapadapter.h
googlemapadapter.cpp