-- AUTO-GENERATED by scripts/generate-sdk.py. Do not edit by hand.
-- Natural wrappers over apiCall(method, params). Refresh with sanitize-commit.
--
-- apiCall/apiCallList are installed natively by the host (they capture the
-- per-source id in a C closure, so they cannot be pure Lua). Everything else
-- in the Serial Studio scripting surface is defined below.

SerialStudio = { Base64 = 0, Hex = 1, Text = 2 }

local _b64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

-- Encodes a raw byte string as base64 (pure Lua, no host dependency).
local function _toBase64(bytes)
  local out, n = {}, #bytes
  for i = 1, n, 3 do
    local b1 = bytes:byte(i) or 0
    local b2 = bytes:byte(i + 1)
    local b3 = bytes:byte(i + 2)
    local n1 = b1 >> 2
    local n2 = ((b1 & 3) << 4) | ((b2 or 0) >> 4)
    local n3 = ((((b2 or 0) & 15) << 2) | ((b3 or 0) >> 6))
    local n4 = (b3 or 0) & 63
    out[#out + 1] = _b64:sub(n1 + 1, n1 + 1)
    out[#out + 1] = _b64:sub(n2 + 1, n2 + 1)
    out[#out + 1] = b2 and _b64:sub(n3 + 1, n3 + 1) or '='
    out[#out + 1] = b3 and _b64:sub(n4 + 1, n4 + 1) or '='
  end
  return table.concat(out)
end

function SerialStudio._encode(value, encoding)
  if encoding == SerialStudio.Hex then
    local hex = tostring(value):gsub('%X', '')
    local bin = {}
    for i = 1, #hex, 2 do
      bin[#bin + 1] = string.char(tonumber(hex:sub(i, i + 1), 16) or 0)
    end
    return _toBase64(table.concat(bin))
  elseif encoding == SerialStudio.Text then
    return _toBase64(tostring(value))
  end
  return value
end

-- Hand-maintained SDK prelude (Lua). Prepended to the generated wrappers by
-- scripts/generate-sdk.py.
--
-- Unlike JavaScript, the Lua bridge functions are installed by the host as
-- native C closures (they capture per-source state), so there is no glue to
-- define here. This block documents the globals each engine may provide:
--
--   Data tables / dataset access (FrameBuilder):
--     tableGet(table, row)        tableSet(table, row, value)
--     datasetGetRaw(uniqueId)     datasetGetFinal(uniqueId)
--     mqttPublish(topic, payload, qos, retain)   -- commercial builds only
--
--   Device output:
--     deviceWrite(data, sourceId)   actionFire(actionId)
--
-- Whether a given global exists depends on which engine is running the script.

api = api or {}
assistant = assistant or {}
assistant.dataset = assistant.dataset or {}
assistant.project = assistant.project or {}
assistant.script = assistant.script or {}
assistant.workspace = assistant.workspace or {}
console = console or {}
consoleExport = consoleExport or {}
controlScript = controlScript or {}
csvExport = csvExport or {}
csvPlayer = csvPlayer or {}
dashboard = dashboard or {}
extensions = extensions or {}
io = io or {}
io.audio = io.audio or {}
io.ble = io.ble or {}
io.canbus = io.canbus or {}
io.hid = io.hid or {}
io.modbus = io.modbus or {}
io.network = io.network or {}
io.process = io.process or {}
io.uart = io.uart or {}
io.usb = io.usb or {}
licensing = licensing or {}
mdf4Export = mdf4Export or {}
mdf4Player = mdf4Player or {}
notifications = notifications or {}
project = project or {}
project.action = project.action or {}
project.dashboard = project.dashboard or {}
project.dataTable = project.dataTable or {}
project.dataset = project.dataset or {}
project.dataset.transform = project.dataset.transform or {}
project.dryRun = project.dryRun or {}
project.frameParser = project.frameParser or {}
project.group = project.group or {}
project.mqtt = project.mqtt or {}
project.mqtt.publisher = project.mqtt.publisher or {}
project.mqtt.subscriber = project.mqtt.subscriber or {}
project.outputWidget = project.outputWidget or {}
project.painter = project.painter or {}
project.source = project.source or {}
project.template = project.template or {}
project.workspace = project.workspace or {}
scripts = scripts or {}
sessions = sessions or {}
system = system or {}
ui = ui or {}
ui.window = ui.window or {}

function api.getCommands()
  local p = {}
  return apiCall('api.getCommands', p)
end

function assistant.checkpoint(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('assistant.checkpoint', p)
end

function assistant.dataset.resolve(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('assistant.dataset.resolve', p)
end

function assistant.listCheckpoints(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('assistant.listCheckpoints', p)
end

function assistant.project.bulkApply(ops)
  local p = {}
  p['ops'] = ops
  return apiCall('assistant.project.bulkApply', p)
end

function assistant.restore(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('assistant.restore', p)
end

function assistant.script.apply(kind, code, options)
  local p = {}
  p['kind'] = kind
  p['code'] = code
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('assistant.script.apply', p)
end

function assistant.script.dryRun(kind, options)
  local p = {}
  p['kind'] = kind
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('assistant.script.dryRun', p)
end

function assistant.snapshot(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('assistant.snapshot', p)
end

function assistant.workspace.addTile(widgetType, options)
  local p = {}
  p['widgetType'] = widgetType
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('assistant.workspace.addTile', p)
end

function assistant.workspace.plan(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('assistant.workspace.plan', p)
end

function assistant.workspace.resolve(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('assistant.workspace.resolve', p)
end

function console.clear()
  local p = {}
  return apiCall('console.clear', p)
end

function console.getConfig()
  local p = {}
  return apiCall('console.getConfig', p)
end

function console.send(data)
  local p = {}
  p['data'] = data
  return apiCall('console.send', p)
end

function console.setAnsiColorsEnabled(enabled)
  local p = {}
  p['enabled'] = enabled
  return apiCall('console.setAnsiColorsEnabled', p)
end

function console.setChecksumMethod(methodIndex)
  local p = {}
  p['methodIndex'] = methodIndex
  return apiCall('console.setChecksumMethod', p)
end

function console.setDataMode(modeIndex)
  local p = {}
  p['modeIndex'] = modeIndex
  return apiCall('console.setDataMode', p)
end

function console.setDisplayMode(modeIndex)
  local p = {}
  p['modeIndex'] = modeIndex
  return apiCall('console.setDisplayMode', p)
end

function console.setEcho(enabled)
  local p = {}
  p['enabled'] = enabled
  return apiCall('console.setEcho', p)
end

function console.setEncoding(encoding)
  local p = {}
  p['encoding'] = encoding
  return apiCall('console.setEncoding', p)
end

function console.setFontFamily(fontFamily)
  local p = {}
  p['fontFamily'] = fontFamily
  return apiCall('console.setFontFamily', p)
end

function console.setFontSize(fontSize)
  local p = {}
  p['fontSize'] = fontSize
  return apiCall('console.setFontSize', p)
end

function console.setLineEnding(endingIndex)
  local p = {}
  p['endingIndex'] = endingIndex
  return apiCall('console.setLineEnding', p)
end

function console.setShowTimestamp(enabled)
  local p = {}
  p['enabled'] = enabled
  return apiCall('console.setShowTimestamp', p)
end

function console.setVt100Emulation(enabled)
  local p = {}
  p['enabled'] = enabled
  return apiCall('console.setVt100Emulation', p)
end

function consoleExport.close()
  local p = {}
  return apiCall('consoleExport.close', p)
end

function consoleExport.getStatus()
  local p = {}
  return apiCall('consoleExport.getStatus', p)
end

function consoleExport.setEnabled(enabled)
  local p = {}
  p['enabled'] = enabled
  return apiCall('consoleExport.setEnabled', p)
end

function controlScript.dryRun(code)
  local p = {}
  p['code'] = code
  return apiCall('controlScript.dryRun', p)
end

function controlScript.get()
  local p = {}
  return apiCall('controlScript.get', p)
end

function controlScript.getCode()
  local p = {}
  return apiCall('controlScript.getCode', p)
end

function controlScript.getStatus()
  local p = {}
  return apiCall('controlScript.getStatus', p)
end

function controlScript.set(code)
  local p = {}
  p['code'] = code
  return apiCall('controlScript.set', p)
end

function controlScript.setCode(code)
  local p = {}
  p['code'] = code
  return apiCall('controlScript.setCode', p)
end

function csvExport.close()
  local p = {}
  return apiCall('csvExport.close', p)
end

function csvExport.getStatus()
  local p = {}
  return apiCall('csvExport.getStatus', p)
end

function csvExport.setEnabled(enabled)
  local p = {}
  p['enabled'] = enabled
  return apiCall('csvExport.setEnabled', p)
end

function csvPlayer.close()
  local p = {}
  return apiCall('csvPlayer.close', p)
end

function csvPlayer.getStatus()
  local p = {}
  return apiCall('csvPlayer.getStatus', p)
end

function csvPlayer.open(filePath)
  local p = {}
  p['filePath'] = filePath
  return apiCall('csvPlayer.open', p)
end

function csvPlayer.setPaused(paused)
  local p = {}
  p['paused'] = paused
  return apiCall('csvPlayer.setPaused', p)
end

function csvPlayer.setProgress(progress)
  local p = {}
  p['progress'] = progress
  return apiCall('csvPlayer.setProgress', p)
end

function csvPlayer.step(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('csvPlayer.step', p)
end

function dashboard.getData()
  local p = {}
  return apiCall('dashboard.getData', p)
end

function dashboard.getFps()
  local p = {}
  return apiCall('dashboard.getFps', p)
end

function dashboard.getOperationMode()
  local p = {}
  return apiCall('dashboard.getOperationMode', p)
end

function dashboard.getStatus()
  local p = {}
  return apiCall('dashboard.getStatus', p)
end

function dashboard.getTimeRange()
  local p = {}
  return apiCall('dashboard.getTimeRange', p)
end

function dashboard.reprocess()
  local p = {}
  return apiCall('dashboard.reprocess', p)
end

function dashboard.setFps(fps)
  local p = {}
  p['fps'] = fps
  return apiCall('dashboard.setFps', p)
end

function dashboard.setOperationMode(mode)
  local p = {}
  p['mode'] = mode
  return apiCall('dashboard.setOperationMode', p)
end

function dashboard.setTimeRange(seconds)
  local p = {}
  p['seconds'] = seconds
  return apiCall('dashboard.setTimeRange', p)
end

function dashboard.tailFrames(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('dashboard.tailFrames', p)
end

function dashboard.tick()
  local p = {}
  return apiCall('dashboard.tick', p)
end

function extensions.addRepository(url)
  local p = {}
  p['url'] = url
  return apiCall('extensions.addRepository', p)
end

function extensions.getInfo(extensionId)
  local p = {}
  p['extensionId'] = extensionId
  return apiCall('extensions.getInfo', p)
end

function extensions.install(addonIndex)
  local p = {}
  p['addonIndex'] = addonIndex
  return apiCall('extensions.install', p)
end

function extensions.list()
  local p = {}
  return apiCall('extensions.list', p)
end

function extensions.listRepositories()
  local p = {}
  return apiCall('extensions.listRepositories', p)
end

function extensions.loadState(pluginId)
  local p = {}
  p['pluginId'] = pluginId
  return apiCall('extensions.loadState', p)
end

function extensions.refresh()
  local p = {}
  return apiCall('extensions.refresh', p)
end

function extensions.removeRepository(index)
  local p = {}
  p['index'] = index
  return apiCall('extensions.removeRepository', p)
end

function extensions.saveState(pluginId, state)
  local p = {}
  p['pluginId'] = pluginId
  p['state'] = state
  return apiCall('extensions.saveState', p)
end

function extensions.uninstall(addonIndex, options)
  local p = {}
  p['addonIndex'] = addonIndex
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('extensions.uninstall', p)
end

function io.audio.getConfig()
  local p = {}
  return apiCall('io.audio.getConfig', p)
end

function io.audio.listInputDevices()
  local p = {}
  return apiCall('io.audio.listInputDevices', p)
end

function io.audio.listInputFormats()
  local p = {}
  return apiCall('io.audio.listInputFormats', p)
end

function io.audio.listOutputDevices()
  local p = {}
  return apiCall('io.audio.listOutputDevices', p)
end

function io.audio.listOutputFormats()
  local p = {}
  return apiCall('io.audio.listOutputFormats', p)
end

function io.audio.listSampleRates()
  local p = {}
  return apiCall('io.audio.listSampleRates', p)
end

function io.audio.setInputChannelConfig(channelIndex)
  local p = {}
  p['channelIndex'] = channelIndex
  return apiCall('io.audio.setInputChannelConfig', p)
end

function io.audio.setInputDevice(deviceIndex)
  local p = {}
  p['deviceIndex'] = deviceIndex
  return apiCall('io.audio.setInputDevice', p)
end

function io.audio.setInputSampleFormat(formatIndex)
  local p = {}
  p['formatIndex'] = formatIndex
  return apiCall('io.audio.setInputSampleFormat', p)
end

function io.audio.setOutputChannelConfig(channelIndex)
  local p = {}
  p['channelIndex'] = channelIndex
  return apiCall('io.audio.setOutputChannelConfig', p)
end

function io.audio.setOutputDevice(deviceIndex)
  local p = {}
  p['deviceIndex'] = deviceIndex
  return apiCall('io.audio.setOutputDevice', p)
end

function io.audio.setOutputSampleFormat(formatIndex)
  local p = {}
  p['formatIndex'] = formatIndex
  return apiCall('io.audio.setOutputSampleFormat', p)
end

function io.audio.setSampleRate(rateIndex)
  local p = {}
  p['rateIndex'] = rateIndex
  return apiCall('io.audio.setSampleRate', p)
end

function io.ble.getConfig()
  local p = {}
  return apiCall('io.ble.getConfig', p)
end

function io.ble.getStatus()
  local p = {}
  return apiCall('io.ble.getStatus', p)
end

function io.ble.listCharacteristics()
  local p = {}
  return apiCall('io.ble.listCharacteristics', p)
end

function io.ble.listDevices()
  local p = {}
  return apiCall('io.ble.listDevices', p)
end

function io.ble.listServices()
  local p = {}
  return apiCall('io.ble.listServices', p)
end

function io.ble.selectDevice(deviceIndex)
  local p = {}
  p['deviceIndex'] = deviceIndex
  return apiCall('io.ble.selectDevice', p)
end

function io.ble.selectService(serviceIndex)
  local p = {}
  p['serviceIndex'] = serviceIndex
  return apiCall('io.ble.selectService', p)
end

function io.ble.selectServiceByUuid(serviceUuid)
  local p = {}
  p['serviceUuid'] = serviceUuid
  return apiCall('io.ble.selectServiceByUuid', p)
end

function io.ble.setCharacteristicIndex(characteristicIndex)
  local p = {}
  p['characteristicIndex'] = characteristicIndex
  return apiCall('io.ble.setCharacteristicIndex', p)
end

function io.ble.setNotifyCharacteristic(characteristicUuid)
  local p = {}
  p['characteristicUuid'] = characteristicUuid
  return apiCall('io.ble.setNotifyCharacteristic', p)
end

function io.ble.startDiscovery()
  local p = {}
  return apiCall('io.ble.startDiscovery', p)
end

function io.ble.writeCharacteristic(characteristicUuid, data, data_encoding)
  local p = {}
  p['characteristicUuid'] = characteristicUuid
  p['data'] = SerialStudio._encode(data, data_encoding)
  return apiCall('io.ble.writeCharacteristic', p)
end

function io.canbus.getConfig()
  local p = {}
  return apiCall('io.canbus.getConfig', p)
end

function io.canbus.getInterfaceError()
  local p = {}
  return apiCall('io.canbus.getInterfaceError', p)
end

function io.canbus.listBitrates()
  local p = {}
  return apiCall('io.canbus.listBitrates', p)
end

function io.canbus.listInterfaces()
  local p = {}
  return apiCall('io.canbus.listInterfaces', p)
end

function io.canbus.listPlugins()
  local p = {}
  return apiCall('io.canbus.listPlugins', p)
end

function io.canbus.setBitrate(bitrate)
  local p = {}
  p['bitrate'] = bitrate
  return apiCall('io.canbus.setBitrate', p)
end

function io.canbus.setCanFd(enabled)
  local p = {}
  p['enabled'] = enabled
  return apiCall('io.canbus.setCanFd', p)
end

function io.canbus.setInterfaceIndex(interfaceIndex)
  local p = {}
  p['interfaceIndex'] = interfaceIndex
  return apiCall('io.canbus.setInterfaceIndex', p)
end

function io.canbus.setPluginIndex(pluginIndex)
  local p = {}
  p['pluginIndex'] = pluginIndex
  return apiCall('io.canbus.setPluginIndex', p)
end

function io.connect()
  local p = {}
  return apiCall('io.connect', p)
end

function io.disconnect()
  local p = {}
  return apiCall('io.disconnect', p)
end

function io.getLatestFrame(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('io.getLatestFrame', p)
end

function io.getStatus()
  local p = {}
  return apiCall('io.getStatus', p)
end

function io.hid.getConfig()
  local p = {}
  return apiCall('io.hid.getConfig', p)
end

function io.hid.listDevices()
  local p = {}
  return apiCall('io.hid.listDevices', p)
end

function io.hid.setDeviceIndex(deviceIndex)
  local p = {}
  p['deviceIndex'] = deviceIndex
  return apiCall('io.hid.setDeviceIndex', p)
end

function io.listBuses()
  local p = {}
  return apiCall('io.listBuses', p)
end

function io.modbus.addRegisterGroup(type, startAddress, count)
  local p = {}
  p['type'] = type
  p['startAddress'] = startAddress
  p['count'] = count
  return apiCall('io.modbus.addRegisterGroup', p)
end

function io.modbus.clearRegisterGroups()
  local p = {}
  return apiCall('io.modbus.clearRegisterGroups', p)
end

function io.modbus.getConfig()
  local p = {}
  return apiCall('io.modbus.getConfig', p)
end

function io.modbus.listBaudRates()
  local p = {}
  return apiCall('io.modbus.listBaudRates', p)
end

function io.modbus.listDataBits()
  local p = {}
  return apiCall('io.modbus.listDataBits', p)
end

function io.modbus.listParities()
  local p = {}
  return apiCall('io.modbus.listParities', p)
end

function io.modbus.listProtocols()
  local p = {}
  return apiCall('io.modbus.listProtocols', p)
end

function io.modbus.listRegisterGroups()
  local p = {}
  return apiCall('io.modbus.listRegisterGroups', p)
end

function io.modbus.listRegisterTypes()
  local p = {}
  return apiCall('io.modbus.listRegisterTypes', p)
end

function io.modbus.listSerialPorts()
  local p = {}
  return apiCall('io.modbus.listSerialPorts', p)
end

function io.modbus.listStopBits()
  local p = {}
  return apiCall('io.modbus.listStopBits', p)
end

function io.modbus.removeRegisterGroup(groupIndex)
  local p = {}
  p['groupIndex'] = groupIndex
  return apiCall('io.modbus.removeRegisterGroup', p)
end

function io.modbus.setBaudRate(baudRate)
  local p = {}
  p['baudRate'] = baudRate
  return apiCall('io.modbus.setBaudRate', p)
end

function io.modbus.setDataBitsIndex(dataBitsIndex)
  local p = {}
  p['dataBitsIndex'] = dataBitsIndex
  return apiCall('io.modbus.setDataBitsIndex', p)
end

function io.modbus.setHost(host)
  local p = {}
  p['host'] = host
  return apiCall('io.modbus.setHost', p)
end

function io.modbus.setParityIndex(parityIndex)
  local p = {}
  p['parityIndex'] = parityIndex
  return apiCall('io.modbus.setParityIndex', p)
end

function io.modbus.setPollInterval(intervalMs)
  local p = {}
  p['intervalMs'] = intervalMs
  return apiCall('io.modbus.setPollInterval', p)
end

function io.modbus.setPort(port)
  local p = {}
  p['port'] = port
  return apiCall('io.modbus.setPort', p)
end

function io.modbus.setProtocolIndex(protocolIndex)
  local p = {}
  p['protocolIndex'] = protocolIndex
  return apiCall('io.modbus.setProtocolIndex', p)
end

function io.modbus.setSerialPortIndex(portIndex)
  local p = {}
  p['portIndex'] = portIndex
  return apiCall('io.modbus.setSerialPortIndex', p)
end

function io.modbus.setSlaveAddress(address)
  local p = {}
  p['address'] = address
  return apiCall('io.modbus.setSlaveAddress', p)
end

function io.modbus.setStopBitsIndex(stopBitsIndex)
  local p = {}
  p['stopBitsIndex'] = stopBitsIndex
  return apiCall('io.modbus.setStopBitsIndex', p)
end

function io.network.getConfig()
  local p = {}
  return apiCall('io.network.getConfig', p)
end

function io.network.listSocketTypes()
  local p = {}
  return apiCall('io.network.listSocketTypes', p)
end

function io.network.lookup(host)
  local p = {}
  p['host'] = host
  return apiCall('io.network.lookup', p)
end

function io.network.setRemoteAddress(address)
  local p = {}
  p['address'] = address
  return apiCall('io.network.setRemoteAddress', p)
end

function io.network.setSocketType(socketTypeIndex)
  local p = {}
  p['socketTypeIndex'] = socketTypeIndex
  return apiCall('io.network.setSocketType', p)
end

function io.network.setTcpPort(port)
  local p = {}
  p['port'] = port
  return apiCall('io.network.setTcpPort', p)
end

function io.network.setUdpLocalPort(port)
  local p = {}
  p['port'] = port
  return apiCall('io.network.setUdpLocalPort', p)
end

function io.network.setUdpMulticast(enabled)
  local p = {}
  p['enabled'] = enabled
  return apiCall('io.network.setUdpMulticast', p)
end

function io.network.setUdpRemotePort(port)
  local p = {}
  p['port'] = port
  return apiCall('io.network.setUdpRemotePort', p)
end

function io.process.getConfig()
  local p = {}
  return apiCall('io.process.getConfig', p)
end

function io.process.listRunning()
  local p = {}
  return apiCall('io.process.listRunning', p)
end

function io.process.setArguments(arguments)
  local p = {}
  p['arguments'] = arguments
  return apiCall('io.process.setArguments', p)
end

function io.process.setExecutable(executable)
  local p = {}
  p['executable'] = executable
  return apiCall('io.process.setExecutable', p)
end

function io.process.setMode(mode)
  local p = {}
  p['mode'] = mode
  return apiCall('io.process.setMode', p)
end

function io.process.setPipePath(pipePath)
  local p = {}
  p['pipePath'] = pipePath
  return apiCall('io.process.setPipePath', p)
end

function io.process.setWorkingDir(workingDir)
  local p = {}
  p['workingDir'] = workingDir
  return apiCall('io.process.setWorkingDir', p)
end

function io.setBusType(busType)
  local p = {}
  p['busType'] = busType
  return apiCall('io.setBusType', p)
end

function io.setPaused(paused)
  local p = {}
  p['paused'] = paused
  return apiCall('io.setPaused', p)
end

function io.uart.getConfig()
  local p = {}
  return apiCall('io.uart.getConfig', p)
end

function io.uart.listBaudRates()
  local p = {}
  return apiCall('io.uart.listBaudRates', p)
end

function io.uart.listPorts()
  local p = {}
  return apiCall('io.uart.listPorts', p)
end

function io.uart.setAutoReconnect(autoReconnect)
  local p = {}
  p['autoReconnect'] = autoReconnect
  return apiCall('io.uart.setAutoReconnect', p)
end

function io.uart.setBaudRate(baudRate)
  local p = {}
  p['baudRate'] = baudRate
  return apiCall('io.uart.setBaudRate', p)
end

function io.uart.setDataBits(dataBitsIndex)
  local p = {}
  p['dataBitsIndex'] = dataBitsIndex
  return apiCall('io.uart.setDataBits', p)
end

function io.uart.setDevice(device)
  local p = {}
  p['device'] = device
  return apiCall('io.uart.setDevice', p)
end

function io.uart.setDtrEnabled(dtrEnabled)
  local p = {}
  p['dtrEnabled'] = dtrEnabled
  return apiCall('io.uart.setDtrEnabled', p)
end

function io.uart.setFlowControl(flowControlIndex)
  local p = {}
  p['flowControlIndex'] = flowControlIndex
  return apiCall('io.uart.setFlowControl', p)
end

function io.uart.setParity(parityIndex)
  local p = {}
  p['parityIndex'] = parityIndex
  return apiCall('io.uart.setParity', p)
end

function io.uart.setPortIndex(portIndex)
  local p = {}
  p['portIndex'] = portIndex
  return apiCall('io.uart.setPortIndex', p)
end

function io.uart.setStopBits(stopBitsIndex)
  local p = {}
  p['stopBitsIndex'] = stopBitsIndex
  return apiCall('io.uart.setStopBits', p)
end

function io.usb.getConfig()
  local p = {}
  return apiCall('io.usb.getConfig', p)
end

function io.usb.listDevices()
  local p = {}
  return apiCall('io.usb.listDevices', p)
end

function io.usb.setDeviceIndex(deviceIndex)
  local p = {}
  p['deviceIndex'] = deviceIndex
  return apiCall('io.usb.setDeviceIndex', p)
end

function io.usb.setInEndpointIndex(endpointIndex)
  local p = {}
  p['endpointIndex'] = endpointIndex
  return apiCall('io.usb.setInEndpointIndex', p)
end

function io.usb.setIsoPacketSize(size)
  local p = {}
  p['size'] = size
  return apiCall('io.usb.setIsoPacketSize', p)
end

function io.usb.setOutEndpointIndex(endpointIndex)
  local p = {}
  p['endpointIndex'] = endpointIndex
  return apiCall('io.usb.setOutEndpointIndex', p)
end

function io.usb.setTransferMode(mode)
  local p = {}
  p['mode'] = mode
  return apiCall('io.usb.setTransferMode', p)
end

function io.writeData(data, data_encoding)
  local p = {}
  p['data'] = SerialStudio._encode(data, data_encoding)
  return apiCall('io.writeData', p)
end

function licensing.activate()
  local p = {}
  return apiCall('licensing.activate', p)
end

function licensing.deactivate()
  local p = {}
  return apiCall('licensing.deactivate', p)
end

function licensing.enableTrial()
  local p = {}
  return apiCall('licensing.enableTrial', p)
end

function licensing.getGuardStatus()
  local p = {}
  return apiCall('licensing.getGuardStatus', p)
end

function licensing.getStatus()
  local p = {}
  return apiCall('licensing.getStatus', p)
end

function licensing.getTrialStatus()
  local p = {}
  return apiCall('licensing.getTrialStatus', p)
end

function licensing.setLicense(licenseKey)
  local p = {}
  p['licenseKey'] = licenseKey
  return apiCall('licensing.setLicense', p)
end

function licensing.validate()
  local p = {}
  return apiCall('licensing.validate', p)
end

function mdf4Export.close()
  local p = {}
  return apiCall('mdf4Export.close', p)
end

function mdf4Export.getStatus()
  local p = {}
  return apiCall('mdf4Export.getStatus', p)
end

function mdf4Export.setEnabled(enabled)
  local p = {}
  p['enabled'] = enabled
  return apiCall('mdf4Export.setEnabled', p)
end

function mdf4Player.close()
  local p = {}
  return apiCall('mdf4Player.close', p)
end

function mdf4Player.getStatus()
  local p = {}
  return apiCall('mdf4Player.getStatus', p)
end

function mdf4Player.open(filePath)
  local p = {}
  p['filePath'] = filePath
  return apiCall('mdf4Player.open', p)
end

function mdf4Player.setPaused(paused)
  local p = {}
  p['paused'] = paused
  return apiCall('mdf4Player.setPaused', p)
end

function mdf4Player.setProgress(progress)
  local p = {}
  p['progress'] = progress
  return apiCall('mdf4Player.setProgress', p)
end

function mdf4Player.step(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('mdf4Player.step', p)
end

function notifications.clearAll()
  local p = {}
  return apiCall('notifications.clearAll', p)
end

function notifications.clearChannel(channel)
  local p = {}
  p['channel'] = channel
  return apiCall('notifications.clearChannel', p)
end

function notifications.getUnreadCount()
  local p = {}
  return apiCall('notifications.getUnreadCount', p)
end

function notifications.list(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('notifications.list', p)
end

function notifications.listChannels()
  local p = {}
  return apiCall('notifications.listChannels', p)
end

function notifications.markRead()
  local p = {}
  return apiCall('notifications.markRead', p)
end

function notifications.post(level, options)
  local p = {}
  p['level'] = level
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('notifications.post', p)
end

function notifications.resolve(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('notifications.resolve', p)
end

function project.action.add()
  local p = {}
  return apiCall('project.action.add', p)
end

function project.action.delete(actionId)
  local p = {}
  p['actionId'] = actionId
  return apiCall('project.action.delete', p)
end

function project.action.duplicate(actionId)
  local p = {}
  p['actionId'] = actionId
  return apiCall('project.action.duplicate', p)
end

function project.action.list()
  local p = {}
  return apiCall('project.action.list', p)
end

function project.action.update(actionId)
  local p = {}
  p['actionId'] = actionId
  return apiCall('project.action.update', p)
end

function project.activate()
  local p = {}
  return apiCall('project.activate', p)
end

function project.batch(ops)
  local p = {}
  p['ops'] = ops
  return apiCall('project.batch', p)
end

function project.dashboard.getTimeRange()
  local p = {}
  return apiCall('project.dashboard.getTimeRange', p)
end

function project.dashboard.setTimeRange(seconds)
  local p = {}
  p['seconds'] = seconds
  return apiCall('project.dashboard.setTimeRange', p)
end

function project.dataTable.add(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.dataTable.add', p)
end

function project.dataTable.addRegister(table, name, options)
  local p = {}
  p['table'] = table
  p['name'] = name
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.dataTable.addRegister', p)
end

function project.dataTable.delete(name, options)
  local p = {}
  p['name'] = name
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.dataTable.delete', p)
end

function project.dataTable.deleteRegister(table, name, options)
  local p = {}
  p['table'] = table
  p['name'] = name
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.dataTable.deleteRegister', p)
end

function project.dataTable.get(name)
  local p = {}
  p['name'] = name
  return apiCall('project.dataTable.get', p)
end

function project.dataTable.getValue(table, name)
  local p = {}
  p['table'] = table
  p['name'] = name
  return apiCall('project.dataTable.getValue', p)
end

function project.dataTable.list()
  local p = {}
  return apiCall('project.dataTable.list', p)
end

function project.dataTable.rename(oldName, newName)
  local p = {}
  p['oldName'] = oldName
  p['newName'] = newName
  return apiCall('project.dataTable.rename', p)
end

function project.dataTable.setValue(table, name, value)
  local p = {}
  p['table'] = table
  p['name'] = name
  p['value'] = value
  return apiCall('project.dataTable.setValue', p)
end

function project.dataTable.updateRegister(table, name, options)
  local p = {}
  p['table'] = table
  p['name'] = name
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.dataTable.updateRegister', p)
end

function project.dataset.add(groupId, options)
  local p = {}
  p['groupId'] = groupId
  p['options'] = options
  return apiCall('project.dataset.add', p)
end

function project.dataset.addMany(groupId, count, options)
  local p = {}
  p['groupId'] = groupId
  p['count'] = count
  p['options'] = options
  return apiCall('project.dataset.addMany', p)
end

function project.dataset.delete(groupId, datasetId, options)
  local p = {}
  p['groupId'] = groupId
  p['datasetId'] = datasetId
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.dataset.delete', p)
end

function project.dataset.duplicate(groupId, datasetId)
  local p = {}
  p['groupId'] = groupId
  p['datasetId'] = datasetId
  return apiCall('project.dataset.duplicate', p)
end

function project.dataset.getAlarmBands(groupId, datasetId)
  local p = {}
  p['groupId'] = groupId
  p['datasetId'] = datasetId
  return apiCall('project.dataset.getAlarmBands', p)
end

function project.dataset.getByPath(path)
  local p = {}
  p['path'] = path
  return apiCall('project.dataset.getByPath', p)
end

function project.dataset.getByTitle(title, options)
  local p = {}
  p['title'] = title
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.dataset.getByTitle', p)
end

function project.dataset.getByUniqueId(uniqueId)
  local p = {}
  p['uniqueId'] = uniqueId
  return apiCall('project.dataset.getByUniqueId', p)
end

function project.dataset.getExecutionOrder()
  local p = {}
  return apiCall('project.dataset.getExecutionOrder', p)
end

function project.dataset.list()
  local p = {}
  return apiCall('project.dataset.list', p)
end

function project.dataset.move(uniqueId, newPosition, options)
  local p = {}
  p['uniqueId'] = uniqueId
  p['newPosition'] = newPosition
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.dataset.move', p)
end

function project.dataset.setAlarmBands(groupId, datasetId, alarmBands)
  local p = {}
  p['groupId'] = groupId
  p['datasetId'] = datasetId
  p['alarmBands'] = alarmBands
  return apiCall('project.dataset.setAlarmBands', p)
end

function project.dataset.setOption(groupId, datasetId, option, enabled)
  local p = {}
  p['groupId'] = groupId
  p['datasetId'] = datasetId
  p['option'] = option
  p['enabled'] = enabled
  return apiCall('project.dataset.setOption', p)
end

function project.dataset.setOptions(groupId, datasetId, options)
  local p = {}
  p['groupId'] = groupId
  p['datasetId'] = datasetId
  p['options'] = options
  return apiCall('project.dataset.setOptions', p)
end

function project.dataset.setTransformCode(groupId, datasetId, code, options)
  local p = {}
  p['groupId'] = groupId
  p['datasetId'] = datasetId
  p['code'] = code
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.dataset.setTransformCode', p)
end

function project.dataset.setVirtual(groupId, datasetId, virtual)
  local p = {}
  p['groupId'] = groupId
  p['datasetId'] = datasetId
  p['virtual'] = virtual
  return apiCall('project.dataset.setVirtual', p)
end

function project.dataset.transform.dryRun(code, language, values)
  local p = {}
  p['code'] = code
  p['language'] = language
  p['values'] = values
  return apiCall('project.dataset.transform.dryRun', p)
end

function project.dataset.update(groupId, datasetId)
  local p = {}
  p['groupId'] = groupId
  p['datasetId'] = datasetId
  return apiCall('project.dataset.update', p)
end

function project.dryRun.endToEnd(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.dryRun.endToEnd', p)
end

function project.exportJson()
  local p = {}
  return apiCall('project.exportJson', p)
end

function project.frameParser.dryCompile(code, language)
  local p = {}
  p['code'] = code
  p['language'] = language
  return apiCall('project.frameParser.dryCompile', p)
end

function project.frameParser.dryRun(code, language, options)
  local p = {}
  p['code'] = code
  p['language'] = language
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.frameParser.dryRun', p)
end

function project.frameParser.getCode(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.frameParser.getCode', p)
end

function project.frameParser.getConfig()
  local p = {}
  return apiCall('project.frameParser.getConfig', p)
end

function project.frameParser.getLanguage(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.frameParser.getLanguage', p)
end

function project.frameParser.getTemplate(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.frameParser.getTemplate', p)
end

function project.frameParser.getTemplateSchema(template)
  local p = {}
  p['template'] = template
  return apiCall('project.frameParser.getTemplateSchema', p)
end

function project.frameParser.listTemplates()
  local p = {}
  return apiCall('project.frameParser.listTemplates', p)
end

function project.frameParser.setCode(code, options)
  local p = {}
  p['code'] = code
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.frameParser.setCode', p)
end

function project.frameParser.setLanguage(language, options)
  local p = {}
  p['language'] = language
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.frameParser.setLanguage', p)
end

function project.frameParser.setTemplate(template, options)
  local p = {}
  p['template'] = template
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.frameParser.setTemplate', p)
end

function project.frameParser.update(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.frameParser.update', p)
end

function project.getStatus()
  local p = {}
  return apiCall('project.getStatus', p)
end

function project.group.add(title, widgetType)
  local p = {}
  p['title'] = title
  p['widgetType'] = widgetType
  return apiCall('project.group.add', p)
end

function project.group.delete(groupId, options)
  local p = {}
  p['groupId'] = groupId
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.group.delete', p)
end

function project.group.duplicate(groupId)
  local p = {}
  p['groupId'] = groupId
  return apiCall('project.group.duplicate', p)
end

function project.group.list()
  local p = {}
  return apiCall('project.group.list', p)
end

function project.group.move(groupId, newPosition, options)
  local p = {}
  p['groupId'] = groupId
  p['newPosition'] = newPosition
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.group.move', p)
end

function project.group.update(groupId)
  local p = {}
  p['groupId'] = groupId
  return apiCall('project.group.update', p)
end

function project.loadJson(config, options)
  local p = {}
  p['config'] = config
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.loadJson', p)
end

function project.mqtt.publisher.getConfig()
  local p = {}
  return apiCall('project.mqtt.publisher.getConfig', p)
end

function project.mqtt.publisher.getStatus()
  local p = {}
  return apiCall('project.mqtt.publisher.getStatus', p)
end

function project.mqtt.publisher.setConfig(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.mqtt.publisher.setConfig', p)
end

function project.mqtt.subscriber.getConfig()
  local p = {}
  return apiCall('project.mqtt.subscriber.getConfig', p)
end

function project.mqtt.subscriber.getStatus()
  local p = {}
  return apiCall('project.mqtt.subscriber.getStatus', p)
end

function project.mqtt.subscriber.setConfig(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.mqtt.subscriber.setConfig', p)
end

function project.new(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.new', p)
end

function project.open(filePath, options)
  local p = {}
  p['filePath'] = filePath
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.open', p)
end

function project.outputWidget.add(groupId, type)
  local p = {}
  p['groupId'] = groupId
  p['type'] = type
  return apiCall('project.outputWidget.add', p)
end

function project.outputWidget.delete(groupId, widgetId)
  local p = {}
  p['groupId'] = groupId
  p['widgetId'] = widgetId
  return apiCall('project.outputWidget.delete', p)
end

function project.outputWidget.dryRun(code, options)
  local p = {}
  p['code'] = code
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.outputWidget.dryRun', p)
end

function project.outputWidget.duplicate(groupId, widgetId)
  local p = {}
  p['groupId'] = groupId
  p['widgetId'] = widgetId
  return apiCall('project.outputWidget.duplicate', p)
end

function project.outputWidget.get(groupId, widgetId)
  local p = {}
  p['groupId'] = groupId
  p['widgetId'] = widgetId
  return apiCall('project.outputWidget.get', p)
end

function project.outputWidget.update(groupId, widgetId)
  local p = {}
  p['groupId'] = groupId
  p['widgetId'] = widgetId
  return apiCall('project.outputWidget.update', p)
end

function project.painter.dryRun(code)
  local p = {}
  p['code'] = code
  return apiCall('project.painter.dryRun', p)
end

function project.painter.getCode(groupId)
  local p = {}
  p['groupId'] = groupId
  return apiCall('project.painter.getCode', p)
end

function project.painter.setCode(groupId, code)
  local p = {}
  p['groupId'] = groupId
  p['code'] = code
  return apiCall('project.painter.setCode', p)
end

function project.save(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.save', p)
end

function project.setTitle(title)
  local p = {}
  p['title'] = title
  return apiCall('project.setTitle', p)
end

function project.snapshot(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.snapshot', p)
end

function project.source.add()
  local p = {}
  return apiCall('project.source.add', p)
end

function project.source.delete(sourceId)
  local p = {}
  p['sourceId'] = sourceId
  return apiCall('project.source.delete', p)
end

function project.source.getConfig(sourceId)
  local p = {}
  p['sourceId'] = sourceId
  return apiCall('project.source.getConfig', p)
end

function project.source.getFrameParserCode(sourceId)
  local p = {}
  p['sourceId'] = sourceId
  return apiCall('project.source.getFrameParserCode', p)
end

function project.source.list()
  local p = {}
  return apiCall('project.source.list', p)
end

function project.source.setFrameParserCode(sourceId, code)
  local p = {}
  p['sourceId'] = sourceId
  p['code'] = code
  return apiCall('project.source.setFrameParserCode', p)
end

function project.source.setProperties(sourceId, settings)
  local p = {}
  p['sourceId'] = sourceId
  p['settings'] = settings
  return apiCall('project.source.setProperties', p)
end

function project.source.setProperty(sourceId, key, propertyValue)
  local p = {}
  p['sourceId'] = sourceId
  p['key'] = key
  p['propertyValue'] = propertyValue
  return apiCall('project.source.setProperty', p)
end

function project.source.update(sourceId, options)
  local p = {}
  p['sourceId'] = sourceId
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.source.update', p)
end

function project.template.apply(templateId, options)
  local p = {}
  p['templateId'] = templateId
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.template.apply', p)
end

function project.template.list()
  local p = {}
  return apiCall('project.template.list', p)
end

function project.validate()
  local p = {}
  return apiCall('project.validate', p)
end

function project.workspace.add(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.workspace.add', p)
end

function project.workspace.addWidget(workspaceId, groupId, widgetType, options)
  local p = {}
  p['workspaceId'] = workspaceId
  p['groupId'] = groupId
  p['widgetType'] = widgetType
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.workspace.addWidget', p)
end

function project.workspace.autoGenerate()
  local p = {}
  return apiCall('project.workspace.autoGenerate', p)
end

function project.workspace.cleanup(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.workspace.cleanup', p)
end

function project.workspace.clearAll(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.workspace.clearAll', p)
end

function project.workspace.delete(id, options)
  local p = {}
  p['id'] = id
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.workspace.delete', p)
end

function project.workspace.get(id)
  local p = {}
  p['id'] = id
  return apiCall('project.workspace.get', p)
end

function project.workspace.getCustomizeMode()
  local p = {}
  return apiCall('project.workspace.getCustomizeMode', p)
end

function project.workspace.list()
  local p = {}
  return apiCall('project.workspace.list', p)
end

function project.workspace.removeWidget(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.workspace.removeWidget', p)
end

function project.workspace.rename(id, title)
  local p = {}
  p['id'] = id
  p['title'] = title
  return apiCall('project.workspace.rename', p)
end

function project.workspace.reorder(workspaceIds)
  local p = {}
  p['workspaceIds'] = workspaceIds
  return apiCall('project.workspace.reorder', p)
end

function project.workspace.setCustomizeMode(enabled)
  local p = {}
  p['enabled'] = enabled
  return apiCall('project.workspace.setCustomizeMode', p)
end

function project.workspace.update(id, options)
  local p = {}
  p['id'] = id
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.workspace.update', p)
end

function project.workspace.validate(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('project.workspace.validate', p)
end

function scripts.get(kind, id)
  local p = {}
  p['kind'] = kind
  p['id'] = id
  return apiCall('scripts.get', p)
end

function scripts.list(options)
  local p = {}
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('scripts.list', p)
end

function sessions.addTag(label)
  local p = {}
  p['label'] = label
  return apiCall('sessions.addTag', p)
end

function sessions.assignTag(sessionId, tagId)
  local p = {}
  p['sessionId'] = sessionId
  p['tagId'] = tagId
  return apiCall('sessions.assignTag', p)
end

function sessions.close()
  local p = {}
  return apiCall('sessions.close', p)
end

function sessions.delete(sessionId)
  local p = {}
  p['sessionId'] = sessionId
  return apiCall('sessions.delete', p)
end

function sessions.deleteTag(tagId)
  local p = {}
  p['tagId'] = tagId
  return apiCall('sessions.deleteTag', p)
end

function sessions.exportToCsv(sessionId)
  local p = {}
  p['sessionId'] = sessionId
  return apiCall('sessions.exportToCsv', p)
end

function sessions.get(sessionId)
  local p = {}
  p['sessionId'] = sessionId
  return apiCall('sessions.get', p)
end

function sessions.getDbPath(projectTitle)
  local p = {}
  p['projectTitle'] = projectTitle
  return apiCall('sessions.getDbPath', p)
end

function sessions.getStatus()
  local p = {}
  return apiCall('sessions.getStatus', p)
end

function sessions.list()
  local p = {}
  return apiCall('sessions.list', p)
end

function sessions.listTags()
  local p = {}
  return apiCall('sessions.listTags', p)
end

function sessions.openDatabase(filePath)
  local p = {}
  p['filePath'] = filePath
  return apiCall('sessions.openDatabase', p)
end

function sessions.removeTag(sessionId, tagId)
  local p = {}
  p['sessionId'] = sessionId
  p['tagId'] = tagId
  return apiCall('sessions.removeTag', p)
end

function sessions.renameTag(tagId, newLabel)
  local p = {}
  p['tagId'] = tagId
  p['newLabel'] = newLabel
  return apiCall('sessions.renameTag', p)
end

function sessions.replay(sessionId)
  local p = {}
  p['sessionId'] = sessionId
  return apiCall('sessions.replay', p)
end

function sessions.setExportEnabled(enabled)
  local p = {}
  p['enabled'] = enabled
  return apiCall('sessions.setExportEnabled', p)
end

function sessions.setNotes(sessionId, notes)
  local p = {}
  p['sessionId'] = sessionId
  p['notes'] = notes
  return apiCall('sessions.setNotes', p)
end

function system.exec(program, options)
  local p = {}
  p['program'] = program
  if options then for k, v in pairs(options) do p[k] = v end end
  return apiCall('system.exec', p)
end

function system.kill(processId)
  local p = {}
  p['processId'] = processId
  return apiCall('system.kill', p)
end

function system.projectDir()
  local p = {}
  return apiCall('system.projectDir', p)
end

function system.runningProcesses()
  local p = {}
  return apiCall('system.runningProcesses', p)
end

function ui.window.getLayout()
  local p = {}
  return apiCall('ui.window.getLayout', p)
end

function ui.window.getStatus()
  local p = {}
  return apiCall('ui.window.getStatus', p)
end

function ui.window.getWidgetSettings(widgetId)
  local p = {}
  p['widgetId'] = widgetId
  return apiCall('ui.window.getWidgetSettings', p)
end

function ui.window.listGroups()
  local p = {}
  return apiCall('ui.window.listGroups', p)
end

function ui.window.listWindowStates()
  local p = {}
  return apiCall('ui.window.listWindowStates', p)
end

function ui.window.loadLayout()
  local p = {}
  return apiCall('ui.window.loadLayout', p)
end

function ui.window.saveLayout()
  local p = {}
  return apiCall('ui.window.saveLayout', p)
end

function ui.window.setActiveGroup(groupId)
  local p = {}
  p['groupId'] = groupId
  return apiCall('ui.window.setActiveGroup', p)
end

function ui.window.setActiveGroupIndex(index)
  local p = {}
  p['index'] = index
  return apiCall('ui.window.setActiveGroupIndex', p)
end

function ui.window.setAutoLayout(enabled)
  local p = {}
  p['enabled'] = enabled
  return apiCall('ui.window.setAutoLayout', p)
end

function ui.window.setLayout(layout)
  local p = {}
  p['layout'] = layout
  return apiCall('ui.window.setLayout', p)
end

function ui.window.setWidgetSetting(widgetId, key, settingValue)
  local p = {}
  p['widgetId'] = widgetId
  p['key'] = key
  p['settingValue'] = settingValue
  return apiCall('ui.window.setWidgetSetting', p)
end

function ui.window.setWindowState(id, state)
  local p = {}
  p['id'] = id
  p['state'] = state
  return apiCall('ui.window.setWindowState', p)
end
