// AUTO-GENERATED by scripts/generate-sdk.py. Do not edit by hand.
// Natural wrappers over apiCall(method, params). Refresh with sanitize-commit.

var SerialStudio = {
  Base64: 0,
  Hex: 1,
  Text: 2,

  _b64: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/',

  _toBase64: function(bytes) {
    var out = '', n = bytes.length;
    for (var i = 0; i < n; i += 3) {
      var b1 = bytes[i] & 0xff;
      var has2 = i + 1 < n, has3 = i + 2 < n;
      var b2 = has2 ? (bytes[i + 1] & 0xff) : 0;
      var b3 = has3 ? (bytes[i + 2] & 0xff) : 0;
      var t = (b1 << 16) | (b2 << 8) | b3;
      out += this._b64.charAt((t >> 18) & 0x3f);
      out += this._b64.charAt((t >> 12) & 0x3f);
      out += has2 ? this._b64.charAt((t >> 6) & 0x3f) : '=';
      out += has3 ? this._b64.charAt(t & 0x3f) : '=';
    }
    return out;
  },

  _encode: function(value, encoding) {
    if (encoding === SerialStudio.Hex) {
      var hex = String(value).replace(/[^0-9a-fA-F]/g, ''), bytes = [];
      for (var i = 0; i < hex.length; i += 2)
        bytes.push(parseInt(hex.substr(i, 2), 16));
      return SerialStudio._toBase64(bytes);
    }
    if (encoding === SerialStudio.Text) {
      var s = String(value), out = [];
      for (var j = 0; j < s.length; ++j)
        out.push(s.charCodeAt(j) & 0xff);
      return SerialStudio._toBase64(out);
    }
    return value;  // already base64
  }
};

// Core gateway. The host installs the bridge object as __ss_bridge; every
// wrapper below routes through apiCall. delay() exists only where the host
// bridge provides it (the control script's worker thread).
function apiCall(method, params) { return __ss_bridge.call(method, params || {}); }
function apiCallList()           { return __ss_bridge.listCommands(); }
function delay(ms)               { if (__ss_bridge.delay) __ss_bridge.delay(ms); }

// Hand-maintained SDK prelude (JavaScript). Prepended to the generated command
// wrappers by scripts/generate-sdk.py to form SerialStudio.js -- the single,
// auditable definition of every global a Serial Studio script can call.
//
// The host (C++) installs only the bridge QObjects (__ss, __ss_db, ...). This
// file defines the friendly globals on top of them. Each block is guarded so it
// no-ops when its bridge is absent; function-expression form keeps the guards
// reliable in block scope.

// Notification levels (always available).
var Info = 0, Warning = 1, Critical = 2;

// Data tables and dataset value access (bridge: __ss, FrameBuilder).
if (typeof __ss !== 'undefined') {
  tableGet        = function(t, r)    { return __ss.tableGet(t, r); };
  tableSet        = function(t, r, v) { __ss.tableSet(t, r, v); };
  datasetGetRaw   = function(uid)     { return __ss.datasetGetRaw(uid); };
  datasetGetFinal = function(uid)     { return __ss.datasetGetFinal(uid); };
  if (__ss.mqttPublish)
    mqttPublish = function(t, p, q, r) { return __ss.mqttPublish(t, p, q, r); };
} else if (typeof __ss_control !== 'undefined' && typeof __ss_bridge !== 'undefined') {
  // Control scripts run on a worker thread with no direct __ss bridge; route the
  // table API through the marshalled apiCall so reads/writes happen on the GUI
  // thread. tableGet returns undefined when the table or register does not exist
  // (so `tableGet(t, r) || fallback` keeps working).
  tableGet = function(t, r) {
    var res = __ss_bridge.call('project.dataTable.getValue', { table: t, name: r });
    return (res.ok && res.result) ? res.result.value : undefined;
  };
  tableSet = function(t, r, v) {
    __ss_bridge.call('project.dataTable.setValue', { table: t, name: r, value: v });
  };
}

// Dashboard control (bridge: __ss_db, DashboardApi).
if (typeof __ss_db !== 'undefined') {
  clearPlots                = function()         { return __ss_db.clearPlots(); };
  setPlotPoints             = function(n)        { return __ss_db.setPlotPoints(n); };
  setTerminalVisible        = function(v)        { return __ss_db.setTerminalVisible(v); };
  setNotificationLogVisible = function(v)        { return __ss_db.setNotificationLogVisible(v); };
  setClockVisible           = function(v)        { return __ss_db.setClockVisible(v); };
  setStopwatchVisible       = function(v)        { return __ss_db.setStopwatchVisible(v); };
  setActiveWorkspace        = function(idOrName) { return __ss_db.setActiveWorkspace(idOrName); };
}

// Device output (bridge: __ss_dw, DeviceWriteApi).
if (typeof __ss_dw !== 'undefined')
  deviceWrite = function(data, sourceId) { return __ss_dw.write(data, sourceId); };

// Action firing (bridge: __ss_af, ActionFireApi).
if (typeof __ss_af !== 'undefined')
  actionFire = function(actionId) { return __ss_af.fire(actionId); };

// Notifications (bridge: __nc, NotificationCenter; Pro only). Accepts (title),
// (title, subtitle), or (channel, title, subtitle).
function __ssNotifyArgs(args) {
  if (args.length <= 1)   return ['Dashboard', args[0] || '', ''];
  if (args.length === 2)  return ['Dashboard', args[0] || '', args[1] || ''];
  return [args[0] || '', args[1] || '', args[2] || ''];
}
if (typeof __nc !== 'undefined') {
  notify = function(level) {
    var a = __ssNotifyArgs(Array.prototype.slice.call(arguments, 1));
    __nc.post(level, a[0], a[1], a[2]);
  };
  notifyInfo     = function() { var a = __ssNotifyArgs(arguments); __nc.postInfo(a[0], a[1], a[2]); };
  notifyWarning  = function() { var a = __ssNotifyArgs(arguments); __nc.postWarning(a[0], a[1], a[2]); };
  notifyCritical = function() { var a = __ssNotifyArgs(arguments); __nc.postCritical(a[0], a[1], a[2]); };
  notifyClear    = function() { var a = __ssNotifyArgs(arguments); __nc.resolve(a[0], a[1], a[2]); };
} else if (typeof __ss_control !== 'undefined' && typeof __ss_bridge !== 'undefined') {
  // Control scripts run on a worker thread with no direct __nc bridge; route notify*
  // through the marshalled apiCall so posting happens on the GUI thread. On non-Pro
  // builds the command is absent and the call returns an error result instead.
  notify = function(level) {
    var a = __ssNotifyArgs(Array.prototype.slice.call(arguments, 1));
    return __ss_bridge.call('notifications.post',
                            { level: level, channel: a[0], title: a[1], subtitle: a[2] });
  };
  notifyInfo = function() {
    var a = __ssNotifyArgs(arguments);
    return notify(Info, a[0], a[1], a[2]);
  };
  notifyWarning = function() {
    var a = __ssNotifyArgs(arguments);
    return notify(Warning, a[0], a[1], a[2]);
  };
  notifyCritical = function() {
    var a = __ssNotifyArgs(arguments);
    return notify(Critical, a[0], a[1], a[2]);
  };
  notifyClear = function() {
    var a = __ssNotifyArgs(arguments);
    return __ss_bridge.call('notifications.resolve',
                            { channel: a[0], title: a[1], subtitle: a[2] });
  };
} else {
  var __ssNoPro = function() {
    throw new Error('notify() requires a Pro license. See https://serial-studio.com/pricing');
  };
  notify = notifyInfo = notifyWarning = notifyCritical = notifyClear = __ssNoPro;
}

// Protocol encoders (pure helpers, always available).
function modbusWriteRegister(address, value) {
  var a = address & 0xFFFF, v = Math.round(value) & 0xFFFF;
  return String.fromCharCode((a >> 8) & 0xFF, a & 0xFF, (v >> 8) & 0xFF, v & 0xFF);
}
function modbusWriteCoil(address, on) {
  return modbusWriteRegister(address, on ? 0xFF00 : 0x0000);
}
function modbusWriteFloat(address, value) {
  var buf = new ArrayBuffer(4);
  new DataView(buf).setFloat32(0, value, false);
  var b = new Uint8Array(buf), a = address & 0xFFFF;
  return String.fromCharCode((a >> 8) & 0xFF, a & 0xFF, b[0], b[1], b[2], b[3]);
}
function canSendFrame(id, payload) {
  var canId = id & 0xFFFF, data = '';
  if (typeof payload === 'string')
    data = payload;
  else if (Array.isArray(payload))
    for (var i = 0; i < payload.length; i++)
      data += String.fromCharCode(payload[i] & 0xFF);
  return String.fromCharCode((canId >> 8) & 0xFF, canId & 0xFF, data.length) + data;
}
function canSendValue(id, value, bytes) {
  bytes = bytes || 2;
  var arr = [], v = Math.round(value);
  for (var i = bytes - 1; i >= 0; i--)
    arr.push((v >> (i * 8)) & 0xFF);
  return canSendFrame(id, arr);
}

// Control-script See/Decide/Act helpers (bridge: __ss_bridge, worker thread only).
// newFrame() returns the latest received frame exactly once per arrival (null when
// nothing new); refreshDashboard() re-runs every dataset transform from the last
// received values and republishes the frames to the dashboard (no export side
// effects) -- call it after tableSet() writes so they render while the device is
// silent; ensureDashboard(spec) declaratively creates whatever the spec
// describes that does not exist yet -- groups matched by title, datasets matched
// by parser index inside their group. Existing items are never modified, and the
// last satisfied spec is memoized so calling it every loop() is free.
if (typeof __ss_bridge !== 'undefined') {
  var __ssLastFrameSeq = 0;
  var __ssEnsuredSig   = '';

  newFrame = function(sourceId) {
    var p = {};
    if (typeof sourceId === 'number')
      p.sourceId = sourceId;
    var r = __ss_bridge.call('io.getLatestFrame', p);
    if (!r.ok || !r.result || !r.result.hasData)
      return null;
    if (r.result.sequence === __ssLastFrameSeq)
      return null;
    __ssLastFrameSeq = r.result.sequence;
    return r.result;
  };

  refreshDashboard = function() {
    return __ss_bridge.call('dashboard.reprocess', {});
  };

  var __ssGroupWidgets = {
    datagrid: 0, accelerometer: 1, gyroscope: 2, gps: 3,
    multiplot: 4, none: 5, plot3d: 6, image: 7, painter: 8
  };
  var __ssDatasetBits = {
    plot: 1, fft: 2, bar: 4, gauge: 8, compass: 16, led: 32, waterfall: 64
  };
  var __ssDatasetOptions = function(ds) {
    if (typeof ds.options === 'number')
      return ds.options;
    var bits = 0;
    for (var key in __ssDatasetBits)
      if (ds[key])
        bits |= __ssDatasetBits[key];
    return bits;
  };
  var __ssEnsureFail = function(out, error) {
    out.ok    = false;
    out.error = error || 'ensureDashboard: API call failed';
    return out;
  };

  ensureDashboard = function(spec) {
    var out = { ok: true, createdGroups: 0, createdDatasets: 0 };
    if (!spec || !spec.length)
      return out;

    var sig = JSON.stringify(spec);
    if (sig === __ssEnsuredSig)
      return out;

    var groupsRes = __ss_bridge.call('project.group.list', {});
    var dsRes     = __ss_bridge.call('project.dataset.list', {});
    if (!groupsRes.ok || !dsRes.ok)
      return __ssEnsureFail(out, groupsRes.error || dsRes.error);

    var groups   = groupsRes.result.groups || [];
    var datasets = dsRes.result.datasets || [];

    for (var g = 0; g < spec.length; ++g) {
      var want    = spec[g];
      var groupId = -1;
      for (var i = 0; i < groups.length; ++i)
        if (groups[i].title === want.title) { groupId = groups[i].groupId; break; }

      if (groupId < 0) {
        var widgetType = __ssGroupWidgets[want.widget || 'none'];
        if (typeof widgetType !== 'number')
          widgetType = __ssGroupWidgets.none;
        var added = __ss_bridge.call('project.group.add',
                                     { title: want.title, widgetType: widgetType });
        if (!added.ok)
          return __ssEnsureFail(out, added.error);
        var relist = __ss_bridge.call('project.group.list', {});
        if (!relist.ok)
          return __ssEnsureFail(out, relist.error);
        groups = relist.result.groups || [];
        for (var j = 0; j < groups.length; ++j)
          if (groups[j].title === want.title) { groupId = groups[j].groupId; break; }
        if (groupId < 0)
          return __ssEnsureFail(out, 'ensureDashboard: group missing after add');
        out.createdGroups++;
      }

      var have = {};
      for (var d = 0; d < datasets.length; ++d)
        if (datasets[d].groupId === groupId)
          have[datasets[d].index] = true;

      var wantDs = want.datasets || [];
      for (var k = 0; k < wantDs.length; ++k) {
        var ds = wantDs[k];
        if (have[ds.index])
          continue;

        var addDs = __ss_bridge.call('project.dataset.addMany', {
          groupId: groupId,
          count: 1,
          options: __ssDatasetOptions(ds),
          titlePattern: ds.title || ('Channel ' + ds.index),
          startIndex: ds.index
        });
        if (!addDs.ok)
          return __ssEnsureFail(out, addDs.error);

        var created = ((addDs.result && addDs.result.created) || [])[0];
        if (ds.units && created)
          __ss_bridge.call('project.dataset.update',
                           { groupId: groupId, datasetId: created.datasetId, units: ds.units });
        out.createdDatasets++;
      }
    }

    __ssEnsuredSig = sig;
    return out;
  };
}

var api = (typeof api !== 'undefined') ? api : {};
var assistant = (typeof assistant !== 'undefined') ? assistant : {};
assistant.dataset = assistant.dataset || {};
assistant.project = assistant.project || {};
assistant.script = assistant.script || {};
assistant.workspace = assistant.workspace || {};
var console = (typeof console !== 'undefined') ? console : {};
var consoleExport = (typeof consoleExport !== 'undefined') ? consoleExport : {};
var controlscript = (typeof controlscript !== 'undefined') ? controlscript : {};
var csvExport = (typeof csvExport !== 'undefined') ? csvExport : {};
var csvPlayer = (typeof csvPlayer !== 'undefined') ? csvPlayer : {};
var dashboard = (typeof dashboard !== 'undefined') ? dashboard : {};
var extensions = (typeof extensions !== 'undefined') ? extensions : {};
var io = (typeof io !== 'undefined') ? io : {};
io.audio = io.audio || {};
io.ble = io.ble || {};
io.canbus = io.canbus || {};
io.hid = io.hid || {};
io.modbus = io.modbus || {};
io.network = io.network || {};
io.process = io.process || {};
io.uart = io.uart || {};
io.usb = io.usb || {};
var licensing = (typeof licensing !== 'undefined') ? licensing : {};
var mdf4Export = (typeof mdf4Export !== 'undefined') ? mdf4Export : {};
var mdf4Player = (typeof mdf4Player !== 'undefined') ? mdf4Player : {};
var notifications = (typeof notifications !== 'undefined') ? notifications : {};
var project = (typeof project !== 'undefined') ? project : {};
project.action = project.action || {};
project.dashboard = project.dashboard || {};
project.dataTable = project.dataTable || {};
project.dataset = project.dataset || {};
project.dataset.transform = project.dataset.transform || {};
project.dryRun = project.dryRun || {};
project.frameParser = project.frameParser || {};
project.group = project.group || {};
project.mqtt = project.mqtt || {};
project.mqtt.publisher = project.mqtt.publisher || {};
project.mqtt.subscriber = project.mqtt.subscriber || {};
project.outputWidget = project.outputWidget || {};
project.painter = project.painter || {};
project.source = project.source || {};
project.template = project.template || {};
project.workspace = project.workspace || {};
var scripts = (typeof scripts !== 'undefined') ? scripts : {};
var sessions = (typeof sessions !== 'undefined') ? sessions : {};
var ui = (typeof ui !== 'undefined') ? ui : {};
ui.window = ui.window || {};

api.getCommands = function() {
  var p = {};
  return apiCall('api.getCommands', p);
};

assistant.checkpoint = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('assistant.checkpoint', p);
};

assistant.dataset.resolve = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('assistant.dataset.resolve', p);
};

assistant.listCheckpoints = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('assistant.listCheckpoints', p);
};

assistant.project.bulkApply = function(ops) {
  var p = {};
  p['ops'] = ops;
  return apiCall('assistant.project.bulkApply', p);
};

assistant.restore = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('assistant.restore', p);
};

assistant.script.apply = function(kind, code, options) {
  var p = {};
  p['kind'] = kind;
  p['code'] = code;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('assistant.script.apply', p);
};

assistant.script.dryRun = function(kind, code, options) {
  var p = {};
  p['kind'] = kind;
  p['code'] = code;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('assistant.script.dryRun', p);
};

assistant.snapshot = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('assistant.snapshot', p);
};

assistant.workspace.addTile = function(widgetType, options) {
  var p = {};
  p['widgetType'] = widgetType;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('assistant.workspace.addTile', p);
};

assistant.workspace.plan = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('assistant.workspace.plan', p);
};

assistant.workspace.resolve = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('assistant.workspace.resolve', p);
};

console.clear = function() {
  var p = {};
  return apiCall('console.clear', p);
};

console.getConfig = function() {
  var p = {};
  return apiCall('console.getConfig', p);
};

console.send = function(data, dataEncoding) {
  var p = {};
  p['data'] = SerialStudio._encode(data, dataEncoding);
  return apiCall('console.send', p);
};

console.setAnsiColorsEnabled = function(enabled) {
  var p = {};
  p['enabled'] = enabled;
  return apiCall('console.setAnsiColorsEnabled', p);
};

console.setChecksumMethod = function(methodIndex) {
  var p = {};
  p['methodIndex'] = methodIndex;
  return apiCall('console.setChecksumMethod', p);
};

console.setDataMode = function(modeIndex) {
  var p = {};
  p['modeIndex'] = modeIndex;
  return apiCall('console.setDataMode', p);
};

console.setDisplayMode = function(modeIndex) {
  var p = {};
  p['modeIndex'] = modeIndex;
  return apiCall('console.setDisplayMode', p);
};

console.setEcho = function(enabled) {
  var p = {};
  p['enabled'] = enabled;
  return apiCall('console.setEcho', p);
};

console.setEncoding = function(encoding) {
  var p = {};
  p['encoding'] = encoding;
  return apiCall('console.setEncoding', p);
};

console.setFontFamily = function(fontFamily) {
  var p = {};
  p['fontFamily'] = fontFamily;
  return apiCall('console.setFontFamily', p);
};

console.setFontSize = function(fontSize) {
  var p = {};
  p['fontSize'] = fontSize;
  return apiCall('console.setFontSize', p);
};

console.setLineEnding = function(endingIndex) {
  var p = {};
  p['endingIndex'] = endingIndex;
  return apiCall('console.setLineEnding', p);
};

console.setShowTimestamp = function(enabled) {
  var p = {};
  p['enabled'] = enabled;
  return apiCall('console.setShowTimestamp', p);
};

console.setVt100Emulation = function(enabled) {
  var p = {};
  p['enabled'] = enabled;
  return apiCall('console.setVt100Emulation', p);
};

consoleExport.close = function() {
  var p = {};
  return apiCall('consoleExport.close', p);
};

consoleExport.getStatus = function() {
  var p = {};
  return apiCall('consoleExport.getStatus', p);
};

consoleExport.setEnabled = function(enabled) {
  var p = {};
  p['enabled'] = enabled;
  return apiCall('consoleExport.setEnabled', p);
};

controlscript.dryRun = function(code) {
  var p = {};
  p['code'] = code;
  return apiCall('controlscript.dryRun', p);
};

controlscript.get = function() {
  var p = {};
  return apiCall('controlscript.get', p);
};

controlscript.getCode = function() {
  var p = {};
  return apiCall('controlscript.getCode', p);
};

controlscript.getStatus = function() {
  var p = {};
  return apiCall('controlscript.getStatus', p);
};

controlscript.set = function(code) {
  var p = {};
  p['code'] = code;
  return apiCall('controlscript.set', p);
};

controlscript.setCode = function(code) {
  var p = {};
  p['code'] = code;
  return apiCall('controlscript.setCode', p);
};

csvExport.close = function() {
  var p = {};
  return apiCall('csvExport.close', p);
};

csvExport.getStatus = function() {
  var p = {};
  return apiCall('csvExport.getStatus', p);
};

csvExport.setEnabled = function(enabled) {
  var p = {};
  p['enabled'] = enabled;
  return apiCall('csvExport.setEnabled', p);
};

csvPlayer.close = function() {
  var p = {};
  return apiCall('csvPlayer.close', p);
};

csvPlayer.getStatus = function() {
  var p = {};
  return apiCall('csvPlayer.getStatus', p);
};

csvPlayer.open = function(filePath) {
  var p = {};
  p['filePath'] = filePath;
  return apiCall('csvPlayer.open', p);
};

csvPlayer.setPaused = function(paused) {
  var p = {};
  p['paused'] = paused;
  return apiCall('csvPlayer.setPaused', p);
};

csvPlayer.setProgress = function(progress) {
  var p = {};
  p['progress'] = progress;
  return apiCall('csvPlayer.setProgress', p);
};

csvPlayer.step = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('csvPlayer.step', p);
};

dashboard.getData = function() {
  var p = {};
  return apiCall('dashboard.getData', p);
};

dashboard.getFps = function() {
  var p = {};
  return apiCall('dashboard.getFps', p);
};

dashboard.getOperationMode = function() {
  var p = {};
  return apiCall('dashboard.getOperationMode', p);
};

dashboard.getStatus = function() {
  var p = {};
  return apiCall('dashboard.getStatus', p);
};

dashboard.getTimeRange = function() {
  var p = {};
  return apiCall('dashboard.getTimeRange', p);
};

dashboard.reprocess = function() {
  var p = {};
  return apiCall('dashboard.reprocess', p);
};

dashboard.setFps = function(fps) {
  var p = {};
  p['fps'] = fps;
  return apiCall('dashboard.setFps', p);
};

dashboard.setOperationMode = function(mode) {
  var p = {};
  p['mode'] = mode;
  return apiCall('dashboard.setOperationMode', p);
};

dashboard.setTimeRange = function(seconds) {
  var p = {};
  p['seconds'] = seconds;
  return apiCall('dashboard.setTimeRange', p);
};

dashboard.tailFrames = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('dashboard.tailFrames', p);
};

extensions.addRepository = function(url) {
  var p = {};
  p['url'] = url;
  return apiCall('extensions.addRepository', p);
};

extensions.getInfo = function(extensionId) {
  var p = {};
  p['extensionId'] = extensionId;
  return apiCall('extensions.getInfo', p);
};

extensions.install = function(addonIndex) {
  var p = {};
  p['addonIndex'] = addonIndex;
  return apiCall('extensions.install', p);
};

extensions.list = function() {
  var p = {};
  return apiCall('extensions.list', p);
};

extensions.listRepositories = function() {
  var p = {};
  return apiCall('extensions.listRepositories', p);
};

extensions.loadState = function(pluginId) {
  var p = {};
  p['pluginId'] = pluginId;
  return apiCall('extensions.loadState', p);
};

extensions.refresh = function() {
  var p = {};
  return apiCall('extensions.refresh', p);
};

extensions.removeRepository = function(index) {
  var p = {};
  p['index'] = index;
  return apiCall('extensions.removeRepository', p);
};

extensions.saveState = function(pluginId, state) {
  var p = {};
  p['pluginId'] = pluginId;
  p['state'] = state;
  return apiCall('extensions.saveState', p);
};

extensions.uninstall = function(addonIndex) {
  var p = {};
  p['addonIndex'] = addonIndex;
  return apiCall('extensions.uninstall', p);
};

io.audio.getConfig = function() {
  var p = {};
  return apiCall('io.audio.getConfig', p);
};

io.audio.listInputDevices = function() {
  var p = {};
  return apiCall('io.audio.listInputDevices', p);
};

io.audio.listInputFormats = function() {
  var p = {};
  return apiCall('io.audio.listInputFormats', p);
};

io.audio.listOutputDevices = function() {
  var p = {};
  return apiCall('io.audio.listOutputDevices', p);
};

io.audio.listOutputFormats = function() {
  var p = {};
  return apiCall('io.audio.listOutputFormats', p);
};

io.audio.listSampleRates = function() {
  var p = {};
  return apiCall('io.audio.listSampleRates', p);
};

io.audio.setInputChannelConfig = function(channelIndex) {
  var p = {};
  p['channelIndex'] = channelIndex;
  return apiCall('io.audio.setInputChannelConfig', p);
};

io.audio.setInputDevice = function(deviceIndex) {
  var p = {};
  p['deviceIndex'] = deviceIndex;
  return apiCall('io.audio.setInputDevice', p);
};

io.audio.setInputSampleFormat = function(formatIndex) {
  var p = {};
  p['formatIndex'] = formatIndex;
  return apiCall('io.audio.setInputSampleFormat', p);
};

io.audio.setOutputChannelConfig = function(channelIndex) {
  var p = {};
  p['channelIndex'] = channelIndex;
  return apiCall('io.audio.setOutputChannelConfig', p);
};

io.audio.setOutputDevice = function(deviceIndex) {
  var p = {};
  p['deviceIndex'] = deviceIndex;
  return apiCall('io.audio.setOutputDevice', p);
};

io.audio.setOutputSampleFormat = function(formatIndex) {
  var p = {};
  p['formatIndex'] = formatIndex;
  return apiCall('io.audio.setOutputSampleFormat', p);
};

io.audio.setSampleRate = function(rateIndex) {
  var p = {};
  p['rateIndex'] = rateIndex;
  return apiCall('io.audio.setSampleRate', p);
};

io.ble.getConfig = function() {
  var p = {};
  return apiCall('io.ble.getConfig', p);
};

io.ble.getStatus = function() {
  var p = {};
  return apiCall('io.ble.getStatus', p);
};

io.ble.listCharacteristics = function() {
  var p = {};
  return apiCall('io.ble.listCharacteristics', p);
};

io.ble.listDevices = function() {
  var p = {};
  return apiCall('io.ble.listDevices', p);
};

io.ble.listServices = function() {
  var p = {};
  return apiCall('io.ble.listServices', p);
};

io.ble.selectDevice = function(deviceIndex) {
  var p = {};
  p['deviceIndex'] = deviceIndex;
  return apiCall('io.ble.selectDevice', p);
};

io.ble.selectService = function(serviceIndex) {
  var p = {};
  p['serviceIndex'] = serviceIndex;
  return apiCall('io.ble.selectService', p);
};

io.ble.selectServiceByUuid = function(serviceUuid) {
  var p = {};
  p['serviceUuid'] = serviceUuid;
  return apiCall('io.ble.selectServiceByUuid', p);
};

io.ble.setCharacteristicIndex = function(characteristicIndex) {
  var p = {};
  p['characteristicIndex'] = characteristicIndex;
  return apiCall('io.ble.setCharacteristicIndex', p);
};

io.ble.setNotifyCharacteristic = function(characteristicUuid) {
  var p = {};
  p['characteristicUuid'] = characteristicUuid;
  return apiCall('io.ble.setNotifyCharacteristic', p);
};

io.ble.startDiscovery = function() {
  var p = {};
  return apiCall('io.ble.startDiscovery', p);
};

io.ble.writeCharacteristic = function(characteristicUuid, data, dataEncoding) {
  var p = {};
  p['characteristicUuid'] = characteristicUuid;
  p['data'] = SerialStudio._encode(data, dataEncoding);
  return apiCall('io.ble.writeCharacteristic', p);
};

io.canbus.getConfig = function() {
  var p = {};
  return apiCall('io.canbus.getConfig', p);
};

io.canbus.getInterfaceError = function() {
  var p = {};
  return apiCall('io.canbus.getInterfaceError', p);
};

io.canbus.listBitrates = function() {
  var p = {};
  return apiCall('io.canbus.listBitrates', p);
};

io.canbus.listInterfaces = function() {
  var p = {};
  return apiCall('io.canbus.listInterfaces', p);
};

io.canbus.listPlugins = function() {
  var p = {};
  return apiCall('io.canbus.listPlugins', p);
};

io.canbus.setBitrate = function(bitrate) {
  var p = {};
  p['bitrate'] = bitrate;
  return apiCall('io.canbus.setBitrate', p);
};

io.canbus.setCanFd = function(enabled) {
  var p = {};
  p['enabled'] = enabled;
  return apiCall('io.canbus.setCanFd', p);
};

io.canbus.setInterfaceIndex = function(interfaceIndex) {
  var p = {};
  p['interfaceIndex'] = interfaceIndex;
  return apiCall('io.canbus.setInterfaceIndex', p);
};

io.canbus.setPluginIndex = function(pluginIndex) {
  var p = {};
  p['pluginIndex'] = pluginIndex;
  return apiCall('io.canbus.setPluginIndex', p);
};

io.connect = function() {
  var p = {};
  return apiCall('io.connect', p);
};

io.disconnect = function() {
  var p = {};
  return apiCall('io.disconnect', p);
};

io.getLatestFrame = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('io.getLatestFrame', p);
};

io.getStatus = function() {
  var p = {};
  return apiCall('io.getStatus', p);
};

io.hid.getConfig = function() {
  var p = {};
  return apiCall('io.hid.getConfig', p);
};

io.hid.listDevices = function() {
  var p = {};
  return apiCall('io.hid.listDevices', p);
};

io.hid.setDeviceIndex = function(deviceIndex) {
  var p = {};
  p['deviceIndex'] = deviceIndex;
  return apiCall('io.hid.setDeviceIndex', p);
};

io.listBuses = function() {
  var p = {};
  return apiCall('io.listBuses', p);
};

io.modbus.addRegisterGroup = function(type, startAddress, count) {
  var p = {};
  p['type'] = type;
  p['startAddress'] = startAddress;
  p['count'] = count;
  return apiCall('io.modbus.addRegisterGroup', p);
};

io.modbus.clearRegisterGroups = function() {
  var p = {};
  return apiCall('io.modbus.clearRegisterGroups', p);
};

io.modbus.getConfig = function() {
  var p = {};
  return apiCall('io.modbus.getConfig', p);
};

io.modbus.listBaudRates = function() {
  var p = {};
  return apiCall('io.modbus.listBaudRates', p);
};

io.modbus.listDataBits = function() {
  var p = {};
  return apiCall('io.modbus.listDataBits', p);
};

io.modbus.listParities = function() {
  var p = {};
  return apiCall('io.modbus.listParities', p);
};

io.modbus.listProtocols = function() {
  var p = {};
  return apiCall('io.modbus.listProtocols', p);
};

io.modbus.listRegisterGroups = function() {
  var p = {};
  return apiCall('io.modbus.listRegisterGroups', p);
};

io.modbus.listRegisterTypes = function() {
  var p = {};
  return apiCall('io.modbus.listRegisterTypes', p);
};

io.modbus.listSerialPorts = function() {
  var p = {};
  return apiCall('io.modbus.listSerialPorts', p);
};

io.modbus.listStopBits = function() {
  var p = {};
  return apiCall('io.modbus.listStopBits', p);
};

io.modbus.removeRegisterGroup = function(groupIndex) {
  var p = {};
  p['groupIndex'] = groupIndex;
  return apiCall('io.modbus.removeRegisterGroup', p);
};

io.modbus.setBaudRate = function(baudRate) {
  var p = {};
  p['baudRate'] = baudRate;
  return apiCall('io.modbus.setBaudRate', p);
};

io.modbus.setDataBitsIndex = function(dataBitsIndex) {
  var p = {};
  p['dataBitsIndex'] = dataBitsIndex;
  return apiCall('io.modbus.setDataBitsIndex', p);
};

io.modbus.setHost = function(host) {
  var p = {};
  p['host'] = host;
  return apiCall('io.modbus.setHost', p);
};

io.modbus.setParityIndex = function(parityIndex) {
  var p = {};
  p['parityIndex'] = parityIndex;
  return apiCall('io.modbus.setParityIndex', p);
};

io.modbus.setPollInterval = function(intervalMs) {
  var p = {};
  p['intervalMs'] = intervalMs;
  return apiCall('io.modbus.setPollInterval', p);
};

io.modbus.setPort = function(port) {
  var p = {};
  p['port'] = port;
  return apiCall('io.modbus.setPort', p);
};

io.modbus.setProtocolIndex = function(protocolIndex) {
  var p = {};
  p['protocolIndex'] = protocolIndex;
  return apiCall('io.modbus.setProtocolIndex', p);
};

io.modbus.setSerialPortIndex = function(portIndex) {
  var p = {};
  p['portIndex'] = portIndex;
  return apiCall('io.modbus.setSerialPortIndex', p);
};

io.modbus.setSlaveAddress = function(address) {
  var p = {};
  p['address'] = address;
  return apiCall('io.modbus.setSlaveAddress', p);
};

io.modbus.setStopBitsIndex = function(stopBitsIndex) {
  var p = {};
  p['stopBitsIndex'] = stopBitsIndex;
  return apiCall('io.modbus.setStopBitsIndex', p);
};

io.network.getConfig = function() {
  var p = {};
  return apiCall('io.network.getConfig', p);
};

io.network.listSocketTypes = function() {
  var p = {};
  return apiCall('io.network.listSocketTypes', p);
};

io.network.lookup = function(host) {
  var p = {};
  p['host'] = host;
  return apiCall('io.network.lookup', p);
};

io.network.setRemoteAddress = function(address) {
  var p = {};
  p['address'] = address;
  return apiCall('io.network.setRemoteAddress', p);
};

io.network.setSocketType = function(socketTypeIndex) {
  var p = {};
  p['socketTypeIndex'] = socketTypeIndex;
  return apiCall('io.network.setSocketType', p);
};

io.network.setTcpPort = function(port) {
  var p = {};
  p['port'] = port;
  return apiCall('io.network.setTcpPort', p);
};

io.network.setUdpLocalPort = function(port) {
  var p = {};
  p['port'] = port;
  return apiCall('io.network.setUdpLocalPort', p);
};

io.network.setUdpMulticast = function(enabled) {
  var p = {};
  p['enabled'] = enabled;
  return apiCall('io.network.setUdpMulticast', p);
};

io.network.setUdpRemotePort = function(port) {
  var p = {};
  p['port'] = port;
  return apiCall('io.network.setUdpRemotePort', p);
};

io.process.getConfig = function() {
  var p = {};
  return apiCall('io.process.getConfig', p);
};

io.process.listRunning = function() {
  var p = {};
  return apiCall('io.process.listRunning', p);
};

io.process.setArguments = function(arguments) {
  var p = {};
  p['arguments'] = arguments;
  return apiCall('io.process.setArguments', p);
};

io.process.setExecutable = function(executable) {
  var p = {};
  p['executable'] = executable;
  return apiCall('io.process.setExecutable', p);
};

io.process.setMode = function(mode) {
  var p = {};
  p['mode'] = mode;
  return apiCall('io.process.setMode', p);
};

io.process.setPipePath = function(pipePath) {
  var p = {};
  p['pipePath'] = pipePath;
  return apiCall('io.process.setPipePath', p);
};

io.process.setWorkingDir = function(workingDir) {
  var p = {};
  p['workingDir'] = workingDir;
  return apiCall('io.process.setWorkingDir', p);
};

io.setBusType = function(busType) {
  var p = {};
  p['busType'] = busType;
  return apiCall('io.setBusType', p);
};

io.setPaused = function(paused) {
  var p = {};
  p['paused'] = paused;
  return apiCall('io.setPaused', p);
};

io.uart.getConfig = function() {
  var p = {};
  return apiCall('io.uart.getConfig', p);
};

io.uart.listBaudRates = function() {
  var p = {};
  return apiCall('io.uart.listBaudRates', p);
};

io.uart.listPorts = function() {
  var p = {};
  return apiCall('io.uart.listPorts', p);
};

io.uart.setAutoReconnect = function(autoReconnect) {
  var p = {};
  p['autoReconnect'] = autoReconnect;
  return apiCall('io.uart.setAutoReconnect', p);
};

io.uart.setBaudRate = function(baudRate) {
  var p = {};
  p['baudRate'] = baudRate;
  return apiCall('io.uart.setBaudRate', p);
};

io.uart.setDataBits = function(dataBitsIndex) {
  var p = {};
  p['dataBitsIndex'] = dataBitsIndex;
  return apiCall('io.uart.setDataBits', p);
};

io.uart.setDevice = function(device) {
  var p = {};
  p['device'] = device;
  return apiCall('io.uart.setDevice', p);
};

io.uart.setDtrEnabled = function(dtrEnabled) {
  var p = {};
  p['dtrEnabled'] = dtrEnabled;
  return apiCall('io.uart.setDtrEnabled', p);
};

io.uart.setFlowControl = function(flowControlIndex) {
  var p = {};
  p['flowControlIndex'] = flowControlIndex;
  return apiCall('io.uart.setFlowControl', p);
};

io.uart.setParity = function(parityIndex) {
  var p = {};
  p['parityIndex'] = parityIndex;
  return apiCall('io.uart.setParity', p);
};

io.uart.setPortIndex = function(portIndex) {
  var p = {};
  p['portIndex'] = portIndex;
  return apiCall('io.uart.setPortIndex', p);
};

io.uart.setStopBits = function(stopBitsIndex) {
  var p = {};
  p['stopBitsIndex'] = stopBitsIndex;
  return apiCall('io.uart.setStopBits', p);
};

io.usb.getConfig = function() {
  var p = {};
  return apiCall('io.usb.getConfig', p);
};

io.usb.listDevices = function() {
  var p = {};
  return apiCall('io.usb.listDevices', p);
};

io.usb.setDeviceIndex = function(deviceIndex) {
  var p = {};
  p['deviceIndex'] = deviceIndex;
  return apiCall('io.usb.setDeviceIndex', p);
};

io.usb.setInEndpointIndex = function(endpointIndex) {
  var p = {};
  p['endpointIndex'] = endpointIndex;
  return apiCall('io.usb.setInEndpointIndex', p);
};

io.usb.setIsoPacketSize = function(size) {
  var p = {};
  p['size'] = size;
  return apiCall('io.usb.setIsoPacketSize', p);
};

io.usb.setOutEndpointIndex = function(endpointIndex) {
  var p = {};
  p['endpointIndex'] = endpointIndex;
  return apiCall('io.usb.setOutEndpointIndex', p);
};

io.usb.setTransferMode = function(mode) {
  var p = {};
  p['mode'] = mode;
  return apiCall('io.usb.setTransferMode', p);
};

io.writeData = function(data, dataEncoding) {
  var p = {};
  p['data'] = SerialStudio._encode(data, dataEncoding);
  return apiCall('io.writeData', p);
};

licensing.activate = function() {
  var p = {};
  return apiCall('licensing.activate', p);
};

licensing.deactivate = function() {
  var p = {};
  return apiCall('licensing.deactivate', p);
};

licensing.enableTrial = function() {
  var p = {};
  return apiCall('licensing.enableTrial', p);
};

licensing.getGuardStatus = function() {
  var p = {};
  return apiCall('licensing.getGuardStatus', p);
};

licensing.getStatus = function() {
  var p = {};
  return apiCall('licensing.getStatus', p);
};

licensing.getTrialStatus = function() {
  var p = {};
  return apiCall('licensing.getTrialStatus', p);
};

licensing.setLicense = function(licenseKey) {
  var p = {};
  p['licenseKey'] = licenseKey;
  return apiCall('licensing.setLicense', p);
};

licensing.validate = function() {
  var p = {};
  return apiCall('licensing.validate', p);
};

mdf4Export.close = function() {
  var p = {};
  return apiCall('mdf4Export.close', p);
};

mdf4Export.getStatus = function() {
  var p = {};
  return apiCall('mdf4Export.getStatus', p);
};

mdf4Export.setEnabled = function(enabled) {
  var p = {};
  p['enabled'] = enabled;
  return apiCall('mdf4Export.setEnabled', p);
};

mdf4Player.close = function() {
  var p = {};
  return apiCall('mdf4Player.close', p);
};

mdf4Player.getStatus = function() {
  var p = {};
  return apiCall('mdf4Player.getStatus', p);
};

mdf4Player.open = function(filePath) {
  var p = {};
  p['filePath'] = filePath;
  return apiCall('mdf4Player.open', p);
};

mdf4Player.setPaused = function(paused) {
  var p = {};
  p['paused'] = paused;
  return apiCall('mdf4Player.setPaused', p);
};

mdf4Player.setProgress = function(progress) {
  var p = {};
  p['progress'] = progress;
  return apiCall('mdf4Player.setProgress', p);
};

mdf4Player.step = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('mdf4Player.step', p);
};

notifications.clearAll = function() {
  var p = {};
  return apiCall('notifications.clearAll', p);
};

notifications.clearChannel = function(channel) {
  var p = {};
  p['channel'] = channel;
  return apiCall('notifications.clearChannel', p);
};

notifications.getUnreadCount = function() {
  var p = {};
  return apiCall('notifications.getUnreadCount', p);
};

notifications.list = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('notifications.list', p);
};

notifications.listChannels = function() {
  var p = {};
  return apiCall('notifications.listChannels', p);
};

notifications.markRead = function() {
  var p = {};
  return apiCall('notifications.markRead', p);
};

notifications.post = function(level, options) {
  var p = {};
  p['level'] = level;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('notifications.post', p);
};

notifications.resolve = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('notifications.resolve', p);
};

project.action.add = function() {
  var p = {};
  return apiCall('project.action.add', p);
};

project.action.delete = function(actionId) {
  var p = {};
  p['actionId'] = actionId;
  return apiCall('project.action.delete', p);
};

project.action.duplicate = function(actionId) {
  var p = {};
  p['actionId'] = actionId;
  return apiCall('project.action.duplicate', p);
};

project.action.list = function() {
  var p = {};
  return apiCall('project.action.list', p);
};

project.action.update = function(actionId) {
  var p = {};
  p['actionId'] = actionId;
  return apiCall('project.action.update', p);
};

project.activate = function() {
  var p = {};
  return apiCall('project.activate', p);
};

project.batch = function(ops) {
  var p = {};
  p['ops'] = ops;
  return apiCall('project.batch', p);
};

project.dashboard.getTimeRange = function() {
  var p = {};
  return apiCall('project.dashboard.getTimeRange', p);
};

project.dashboard.setTimeRange = function(seconds) {
  var p = {};
  p['seconds'] = seconds;
  return apiCall('project.dashboard.setTimeRange', p);
};

project.dataTable.add = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.dataTable.add', p);
};

project.dataTable.addRegister = function(table, name, options) {
  var p = {};
  p['table'] = table;
  p['name'] = name;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.dataTable.addRegister', p);
};

project.dataTable.delete = function(name) {
  var p = {};
  p['name'] = name;
  return apiCall('project.dataTable.delete', p);
};

project.dataTable.deleteRegister = function(table, name) {
  var p = {};
  p['table'] = table;
  p['name'] = name;
  return apiCall('project.dataTable.deleteRegister', p);
};

project.dataTable.get = function(name) {
  var p = {};
  p['name'] = name;
  return apiCall('project.dataTable.get', p);
};

project.dataTable.getValue = function(table, name) {
  var p = {};
  p['table'] = table;
  p['name'] = name;
  return apiCall('project.dataTable.getValue', p);
};

project.dataTable.list = function() {
  var p = {};
  return apiCall('project.dataTable.list', p);
};

project.dataTable.rename = function(oldName, newName) {
  var p = {};
  p['oldName'] = oldName;
  p['newName'] = newName;
  return apiCall('project.dataTable.rename', p);
};

project.dataTable.setValue = function(table, name, value) {
  var p = {};
  p['table'] = table;
  p['name'] = name;
  p['value'] = value;
  return apiCall('project.dataTable.setValue', p);
};

project.dataTable.updateRegister = function(table, name, options) {
  var p = {};
  p['table'] = table;
  p['name'] = name;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.dataTable.updateRegister', p);
};

project.dataset.add = function(groupId, options) {
  var p = {};
  p['groupId'] = groupId;
  p['options'] = options;
  return apiCall('project.dataset.add', p);
};

project.dataset.addMany = function(groupId, count, options) {
  var p = {};
  p['groupId'] = groupId;
  p['count'] = count;
  p['options'] = options;
  return apiCall('project.dataset.addMany', p);
};

project.dataset.delete = function(groupId, datasetId, options) {
  var p = {};
  p['groupId'] = groupId;
  p['datasetId'] = datasetId;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.dataset.delete', p);
};

project.dataset.duplicate = function(groupId, datasetId) {
  var p = {};
  p['groupId'] = groupId;
  p['datasetId'] = datasetId;
  return apiCall('project.dataset.duplicate', p);
};

project.dataset.getAlarmBands = function(groupId, datasetId) {
  var p = {};
  p['groupId'] = groupId;
  p['datasetId'] = datasetId;
  return apiCall('project.dataset.getAlarmBands', p);
};

project.dataset.getByPath = function(path) {
  var p = {};
  p['path'] = path;
  return apiCall('project.dataset.getByPath', p);
};

project.dataset.getByTitle = function(title, options) {
  var p = {};
  p['title'] = title;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.dataset.getByTitle', p);
};

project.dataset.getByUniqueId = function(uniqueId) {
  var p = {};
  p['uniqueId'] = uniqueId;
  return apiCall('project.dataset.getByUniqueId', p);
};

project.dataset.getExecutionOrder = function() {
  var p = {};
  return apiCall('project.dataset.getExecutionOrder', p);
};

project.dataset.list = function() {
  var p = {};
  return apiCall('project.dataset.list', p);
};

project.dataset.move = function(uniqueId, newPosition, options) {
  var p = {};
  p['uniqueId'] = uniqueId;
  p['newPosition'] = newPosition;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.dataset.move', p);
};

project.dataset.setAlarmBands = function(groupId, datasetId, alarmBands) {
  var p = {};
  p['groupId'] = groupId;
  p['datasetId'] = datasetId;
  p['alarmBands'] = alarmBands;
  return apiCall('project.dataset.setAlarmBands', p);
};

project.dataset.setOption = function(groupId, datasetId, option, enabled) {
  var p = {};
  p['groupId'] = groupId;
  p['datasetId'] = datasetId;
  p['option'] = option;
  p['enabled'] = enabled;
  return apiCall('project.dataset.setOption', p);
};

project.dataset.setOptions = function(groupId, datasetId, options) {
  var p = {};
  p['groupId'] = groupId;
  p['datasetId'] = datasetId;
  p['options'] = options;
  return apiCall('project.dataset.setOptions', p);
};

project.dataset.setTransformCode = function(groupId, datasetId, code, options) {
  var p = {};
  p['groupId'] = groupId;
  p['datasetId'] = datasetId;
  p['code'] = code;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.dataset.setTransformCode', p);
};

project.dataset.setVirtual = function(groupId, datasetId, virtual) {
  var p = {};
  p['groupId'] = groupId;
  p['datasetId'] = datasetId;
  p['virtual'] = virtual;
  return apiCall('project.dataset.setVirtual', p);
};

project.dataset.transform.dryRun = function(code, language, values) {
  var p = {};
  p['code'] = code;
  p['language'] = language;
  p['values'] = values;
  return apiCall('project.dataset.transform.dryRun', p);
};

project.dataset.update = function(groupId, datasetId) {
  var p = {};
  p['groupId'] = groupId;
  p['datasetId'] = datasetId;
  return apiCall('project.dataset.update', p);
};

project.dryRun.endToEnd = function(sampleFrame, sampleFrames, sourceId, code, language, verbose) {
  var p = {};
  p['sampleFrame'] = sampleFrame;
  p['sampleFrames'] = sampleFrames;
  p['sourceId'] = sourceId;
  p['code'] = code;
  p['language'] = language;
  p['verbose'] = verbose;
  return apiCall('project.dryRun.endToEnd', p);
};

project.exportJson = function() {
  var p = {};
  return apiCall('project.exportJson', p);
};

project.frameParser.dryCompile = function(code, language) {
  var p = {};
  p['code'] = code;
  p['language'] = language;
  return apiCall('project.frameParser.dryCompile', p);
};

project.frameParser.dryRun = function(code, language, inputBytes, inputBytesHex, decoderMethod, frameDetection, frameStart, frameEnd, hexadecimalDelimiters, checksumAlgorithm, operationMode) {
  var p = {};
  p['code'] = code;
  p['language'] = language;
  p['inputBytes'] = inputBytes;
  p['inputBytesHex'] = inputBytesHex;
  p['decoderMethod'] = decoderMethod;
  p['frameDetection'] = frameDetection;
  p['frameStart'] = frameStart;
  p['frameEnd'] = frameEnd;
  p['hexadecimalDelimiters'] = hexadecimalDelimiters;
  p['checksumAlgorithm'] = checksumAlgorithm;
  p['operationMode'] = operationMode;
  return apiCall('project.frameParser.dryRun', p);
};

project.frameParser.getCode = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.frameParser.getCode', p);
};

project.frameParser.getConfig = function() {
  var p = {};
  return apiCall('project.frameParser.getConfig', p);
};

project.frameParser.getLanguage = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.frameParser.getLanguage', p);
};

project.frameParser.getTemplate = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.frameParser.getTemplate', p);
};

project.frameParser.getTemplateSchema = function(template) {
  var p = {};
  p['template'] = template;
  return apiCall('project.frameParser.getTemplateSchema', p);
};

project.frameParser.listTemplates = function() {
  var p = {};
  return apiCall('project.frameParser.listTemplates', p);
};

project.frameParser.setCode = function(code, options) {
  var p = {};
  p['code'] = code;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.frameParser.setCode', p);
};

project.frameParser.setLanguage = function(language, options) {
  var p = {};
  p['language'] = language;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.frameParser.setLanguage', p);
};

project.frameParser.setTemplate = function(template, options) {
  var p = {};
  p['template'] = template;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.frameParser.setTemplate', p);
};

project.frameParser.update = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.frameParser.update', p);
};

project.getStatus = function() {
  var p = {};
  return apiCall('project.getStatus', p);
};

project.group.add = function(title, widgetType) {
  var p = {};
  p['title'] = title;
  p['widgetType'] = widgetType;
  return apiCall('project.group.add', p);
};

project.group.delete = function(groupId, options) {
  var p = {};
  p['groupId'] = groupId;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.group.delete', p);
};

project.group.duplicate = function(groupId) {
  var p = {};
  p['groupId'] = groupId;
  return apiCall('project.group.duplicate', p);
};

project.group.list = function() {
  var p = {};
  return apiCall('project.group.list', p);
};

project.group.move = function(groupId, newPosition, options) {
  var p = {};
  p['groupId'] = groupId;
  p['newPosition'] = newPosition;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.group.move', p);
};

project.group.update = function(groupId) {
  var p = {};
  p['groupId'] = groupId;
  return apiCall('project.group.update', p);
};

project.loadJson = function(config, options) {
  var p = {};
  p['config'] = config;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.loadJson', p);
};

project.mqtt.publisher.getConfig = function() {
  var p = {};
  return apiCall('project.mqtt.publisher.getConfig', p);
};

project.mqtt.publisher.getStatus = function() {
  var p = {};
  return apiCall('project.mqtt.publisher.getStatus', p);
};

project.mqtt.publisher.setConfig = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.mqtt.publisher.setConfig', p);
};

project.mqtt.subscriber.getConfig = function() {
  var p = {};
  return apiCall('project.mqtt.subscriber.getConfig', p);
};

project.mqtt.subscriber.getStatus = function() {
  var p = {};
  return apiCall('project.mqtt.subscriber.getStatus', p);
};

project.mqtt.subscriber.setConfig = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.mqtt.subscriber.setConfig', p);
};

project.new = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.new', p);
};

project.open = function(filePath, options) {
  var p = {};
  p['filePath'] = filePath;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.open', p);
};

project.outputWidget.add = function(groupId, type) {
  var p = {};
  p['groupId'] = groupId;
  p['type'] = type;
  return apiCall('project.outputWidget.add', p);
};

project.outputWidget.delete = function(groupId, widgetId) {
  var p = {};
  p['groupId'] = groupId;
  p['widgetId'] = widgetId;
  return apiCall('project.outputWidget.delete', p);
};

project.outputWidget.dryRun = function(code, inputValue, hex) {
  var p = {};
  p['code'] = code;
  p['inputValue'] = inputValue;
  p['hex'] = hex;
  return apiCall('project.outputWidget.dryRun', p);
};

project.outputWidget.duplicate = function(groupId, widgetId) {
  var p = {};
  p['groupId'] = groupId;
  p['widgetId'] = widgetId;
  return apiCall('project.outputWidget.duplicate', p);
};

project.outputWidget.get = function(groupId, widgetId) {
  var p = {};
  p['groupId'] = groupId;
  p['widgetId'] = widgetId;
  return apiCall('project.outputWidget.get', p);
};

project.outputWidget.update = function(groupId, widgetId) {
  var p = {};
  p['groupId'] = groupId;
  p['widgetId'] = widgetId;
  return apiCall('project.outputWidget.update', p);
};

project.painter.dryRun = function(code) {
  var p = {};
  p['code'] = code;
  return apiCall('project.painter.dryRun', p);
};

project.painter.getCode = function(groupId) {
  var p = {};
  p['groupId'] = groupId;
  return apiCall('project.painter.getCode', p);
};

project.painter.setCode = function(groupId, code) {
  var p = {};
  p['groupId'] = groupId;
  p['code'] = code;
  return apiCall('project.painter.setCode', p);
};

project.save = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.save', p);
};

project.setTitle = function(title) {
  var p = {};
  p['title'] = title;
  return apiCall('project.setTitle', p);
};

project.snapshot = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.snapshot', p);
};

project.source.add = function() {
  var p = {};
  return apiCall('project.source.add', p);
};

project.source.delete = function(sourceId) {
  var p = {};
  p['sourceId'] = sourceId;
  return apiCall('project.source.delete', p);
};

project.source.getConfig = function(sourceId) {
  var p = {};
  p['sourceId'] = sourceId;
  return apiCall('project.source.getConfig', p);
};

project.source.getFrameParserCode = function(sourceId) {
  var p = {};
  p['sourceId'] = sourceId;
  return apiCall('project.source.getFrameParserCode', p);
};

project.source.list = function() {
  var p = {};
  return apiCall('project.source.list', p);
};

project.source.setFrameParserCode = function(sourceId, code) {
  var p = {};
  p['sourceId'] = sourceId;
  p['code'] = code;
  return apiCall('project.source.setFrameParserCode', p);
};

project.source.setProperties = function(sourceId, settings) {
  var p = {};
  p['sourceId'] = sourceId;
  p['settings'] = settings;
  return apiCall('project.source.setProperties', p);
};

project.source.setProperty = function(sourceId, key, propertyValue) {
  var p = {};
  p['sourceId'] = sourceId;
  p['key'] = key;
  p['propertyValue'] = propertyValue;
  return apiCall('project.source.setProperty', p);
};

project.source.update = function(sourceId, options) {
  var p = {};
  p['sourceId'] = sourceId;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.source.update', p);
};

project.template.apply = function(templateId, options) {
  var p = {};
  p['templateId'] = templateId;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.template.apply', p);
};

project.template.list = function() {
  var p = {};
  return apiCall('project.template.list', p);
};

project.validate = function() {
  var p = {};
  return apiCall('project.validate', p);
};

project.workspace.add = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.workspace.add', p);
};

project.workspace.addWidget = function(workspaceId, widgetType, groupId, options) {
  var p = {};
  p['workspaceId'] = workspaceId;
  p['widgetType'] = widgetType;
  p['groupId'] = groupId;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.workspace.addWidget', p);
};

project.workspace.autoGenerate = function() {
  var p = {};
  return apiCall('project.workspace.autoGenerate', p);
};

project.workspace.cleanup = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.workspace.cleanup', p);
};

project.workspace.clearAll = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.workspace.clearAll', p);
};

project.workspace.delete = function(id, options) {
  var p = {};
  p['id'] = id;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.workspace.delete', p);
};

project.workspace.get = function(id) {
  var p = {};
  p['id'] = id;
  return apiCall('project.workspace.get', p);
};

project.workspace.getCustomizeMode = function() {
  var p = {};
  return apiCall('project.workspace.getCustomizeMode', p);
};

project.workspace.list = function() {
  var p = {};
  return apiCall('project.workspace.list', p);
};

project.workspace.removeWidget = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.workspace.removeWidget', p);
};

project.workspace.rename = function(id, title) {
  var p = {};
  p['id'] = id;
  p['title'] = title;
  return apiCall('project.workspace.rename', p);
};

project.workspace.reorder = function(workspaceIds) {
  var p = {};
  p['workspaceIds'] = workspaceIds;
  return apiCall('project.workspace.reorder', p);
};

project.workspace.setCustomizeMode = function(enabled) {
  var p = {};
  p['enabled'] = enabled;
  return apiCall('project.workspace.setCustomizeMode', p);
};

project.workspace.update = function(id, options) {
  var p = {};
  p['id'] = id;
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.workspace.update', p);
};

project.workspace.validate = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('project.workspace.validate', p);
};

scripts.get = function(kind, id) {
  var p = {};
  p['kind'] = kind;
  p['id'] = id;
  return apiCall('scripts.get', p);
};

scripts.list = function(options) {
  var p = {};
  if (options) for (var k in options) p[k] = options[k];
  return apiCall('scripts.list', p);
};

sessions.addTag = function(label) {
  var p = {};
  p['label'] = label;
  return apiCall('sessions.addTag', p);
};

sessions.assignTag = function(sessionId, tagId) {
  var p = {};
  p['sessionId'] = sessionId;
  p['tagId'] = tagId;
  return apiCall('sessions.assignTag', p);
};

sessions.close = function() {
  var p = {};
  return apiCall('sessions.close', p);
};

sessions.delete = function(sessionId) {
  var p = {};
  p['sessionId'] = sessionId;
  return apiCall('sessions.delete', p);
};

sessions.deleteTag = function(tagId) {
  var p = {};
  p['tagId'] = tagId;
  return apiCall('sessions.deleteTag', p);
};

sessions.exportToCsv = function(sessionId) {
  var p = {};
  p['sessionId'] = sessionId;
  return apiCall('sessions.exportToCsv', p);
};

sessions.get = function(sessionId) {
  var p = {};
  p['sessionId'] = sessionId;
  return apiCall('sessions.get', p);
};

sessions.getDbPath = function(projectTitle) {
  var p = {};
  p['projectTitle'] = projectTitle;
  return apiCall('sessions.getDbPath', p);
};

sessions.getStatus = function() {
  var p = {};
  return apiCall('sessions.getStatus', p);
};

sessions.list = function() {
  var p = {};
  return apiCall('sessions.list', p);
};

sessions.listTags = function() {
  var p = {};
  return apiCall('sessions.listTags', p);
};

sessions.openDatabase = function(filePath) {
  var p = {};
  p['filePath'] = filePath;
  return apiCall('sessions.openDatabase', p);
};

sessions.removeTag = function(sessionId, tagId) {
  var p = {};
  p['sessionId'] = sessionId;
  p['tagId'] = tagId;
  return apiCall('sessions.removeTag', p);
};

sessions.renameTag = function(tagId, newLabel) {
  var p = {};
  p['tagId'] = tagId;
  p['newLabel'] = newLabel;
  return apiCall('sessions.renameTag', p);
};

sessions.replay = function(sessionId) {
  var p = {};
  p['sessionId'] = sessionId;
  return apiCall('sessions.replay', p);
};

sessions.setExportEnabled = function(enabled) {
  var p = {};
  p['enabled'] = enabled;
  return apiCall('sessions.setExportEnabled', p);
};

sessions.setNotes = function(sessionId, notes) {
  var p = {};
  p['sessionId'] = sessionId;
  p['notes'] = notes;
  return apiCall('sessions.setNotes', p);
};

ui.window.getLayout = function() {
  var p = {};
  return apiCall('ui.window.getLayout', p);
};

ui.window.getStatus = function() {
  var p = {};
  return apiCall('ui.window.getStatus', p);
};

ui.window.getWidgetSettings = function(widgetId) {
  var p = {};
  p['widgetId'] = widgetId;
  return apiCall('ui.window.getWidgetSettings', p);
};

ui.window.listGroups = function() {
  var p = {};
  return apiCall('ui.window.listGroups', p);
};

ui.window.listWindowStates = function() {
  var p = {};
  return apiCall('ui.window.listWindowStates', p);
};

ui.window.loadLayout = function() {
  var p = {};
  return apiCall('ui.window.loadLayout', p);
};

ui.window.saveLayout = function() {
  var p = {};
  return apiCall('ui.window.saveLayout', p);
};

ui.window.setActiveGroup = function(groupId) {
  var p = {};
  p['groupId'] = groupId;
  return apiCall('ui.window.setActiveGroup', p);
};

ui.window.setActiveGroupIndex = function(index) {
  var p = {};
  p['index'] = index;
  return apiCall('ui.window.setActiveGroupIndex', p);
};

ui.window.setAutoLayout = function(enabled) {
  var p = {};
  p['enabled'] = enabled;
  return apiCall('ui.window.setAutoLayout', p);
};

ui.window.setLayout = function(layout) {
  var p = {};
  p['layout'] = layout;
  return apiCall('ui.window.setLayout', p);
};

ui.window.setWidgetSetting = function(widgetId, key, settingValue) {
  var p = {};
  p['widgetId'] = widgetId;
  p['key'] = key;
  p['settingValue'] = settingValue;
  return apiCall('ui.window.setWidgetSetting', p);
};

ui.window.setWindowState = function(id, state) {
  var p = {};
  p['id'] = id;
  p['state'] = state;
  return apiCall('ui.window.setWindowState', p);
};
