/*
 * Serial Studio
 * https://serial-studio.com/
 *
 * Copyright (C) 2020-2026 Alex Spataru
 *
 * This file is dual-licensed:
 *
 * - Under the GNU GPLv3 (or later) for builds that exclude Pro modules.
 * - Under the Serial Studio Commercial License for builds that include
 *   any Pro functionality.
 *
 * You must comply with the terms of one of these licenses, depending
 * on your use case.
 *
 * For GPL terms, see <https://www.gnu.org/licenses/gpl-3.0.html>
 * For commercial terms, see LICENSES/LicenseRef-SerialStudio-Commercial.txt.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-SerialStudio-Commercial
 */

// AUTO-GENERATED lupdate stub ("Commands" context) from app/rcc/commands/; regenerate, never edit.

#include <QCoreApplication>

// clang-format off
[[maybe_unused]] static const char* const kCommandStrings[] = {
  QT_TRANSLATE_NOOP("Commands", "3D Plot"),
  QT_TRANSLATE_NOOP("Commands", "AI Assistant"),
  QT_TRANSLATE_NOOP("Commands", "AI Wiki & Chat"),
  QT_TRANSLATE_NOOP("Commands", "About"),
  QT_TRANSLATE_NOOP("Commands", "Accelerometer"),
  QT_TRANSLATE_NOOP("Commands", "Action"),
  QT_TRANSLATE_NOOP("Commands", "Add 3D Plot"),
  QT_TRANSLATE_NOOP("Commands", "Add Accelerometer"),
  QT_TRANSLATE_NOOP("Commands", "Add Action"),
  QT_TRANSLATE_NOOP("Commands", "Add Bar Panel"),
  QT_TRANSLATE_NOOP("Commands", "Add Compass"),
  QT_TRANSLATE_NOOP("Commands", "Add Data Table"),
  QT_TRANSLATE_NOOP("Commands", "Add Dataset"),
  QT_TRANSLATE_NOOP("Commands", "Add Device"),
  QT_TRANSLATE_NOOP("Commands", "Add External Window"),
  QT_TRANSLATE_NOOP("Commands", "Add FFT Plot"),
  QT_TRANSLATE_NOOP("Commands", "Add GPS Map"),
  QT_TRANSLATE_NOOP("Commands", "Add Gauge"),
  QT_TRANSLATE_NOOP("Commands", "Add Group"),
  QT_TRANSLATE_NOOP("Commands", "Add Gyroscope"),
  QT_TRANSLATE_NOOP("Commands", "Add Image View"),
  QT_TRANSLATE_NOOP("Commands", "Add LED Indicator"),
  QT_TRANSLATE_NOOP("Commands", "Add Level Indicator"),
  QT_TRANSLATE_NOOP("Commands", "Add Multi-Plot"),
  QT_TRANSLATE_NOOP("Commands", "Add Output Button"),
  QT_TRANSLATE_NOOP("Commands", "Add Output Knob"),
  QT_TRANSLATE_NOOP("Commands", "Add Output Panel"),
  QT_TRANSLATE_NOOP("Commands", "Add Output Slider"),
  QT_TRANSLATE_NOOP("Commands", "Add Output Text Field"),
  QT_TRANSLATE_NOOP("Commands", "Add Output Toggle"),
  QT_TRANSLATE_NOOP("Commands", "Add Painter"),
  QT_TRANSLATE_NOOP("Commands", "Add Plot"),
  QT_TRANSLATE_NOOP("Commands", "Add Web View"),
  QT_TRANSLATE_NOOP("Commands", "Add a 2D plot dataset"),
  QT_TRANSLATE_NOOP("Commands", "Add a 2D plot with multiple signals"),
  QT_TRANSLATE_NOOP("Commands", "Add a 3D plot visualization"),
  QT_TRANSLATE_NOOP("Commands", "Add a Fast Fourier Transform plot"),
  QT_TRANSLATE_NOOP("Commands", "Add a compass widget for directional data"),
  QT_TRANSLATE_NOOP("Commands", "Add a data table view"),
  QT_TRANSLATE_NOOP("Commands", "Add a dataset container group"),
  QT_TRANSLATE_NOOP("Commands", "Add a gauge widget for numeric data"),
  QT_TRANSLATE_NOOP("Commands", "Add a generic dataset"),
  QT_TRANSLATE_NOOP("Commands", "Add a group for 3-axis accelerometer data"),
  QT_TRANSLATE_NOOP("Commands", "Add a group for 3-axis gyroscope data"),
  QT_TRANSLATE_NOOP("Commands", "Add a map widget for GPS data"),
  QT_TRANSLATE_NOOP("Commands", "Add a multi-channel bar panel"),
  QT_TRANSLATE_NOOP("Commands", "Add a new action to the project"),
  QT_TRANSLATE_NOOP("Commands", "Add a new data source (device) to the project"),
  QT_TRANSLATE_NOOP("Commands", "Add a new output control panel with a button"),
  QT_TRANSLATE_NOOP("Commands", "Add a vertical bar level indicator"),
  QT_TRANSLATE_NOOP("Commands", "Add a web viewer"),
  QT_TRANSLATE_NOOP("Commands", "Add an LED-style status indicator"),
  QT_TRANSLATE_NOOP("Commands", "Add an image/video stream viewer"),
  QT_TRANSLATE_NOOP("Commands", "Add an output button control"),
  QT_TRANSLATE_NOOP("Commands", "Add an output knob control"),
  QT_TRANSLATE_NOOP("Commands", "Add an output slider control"),
  QT_TRANSLATE_NOOP("Commands", "Add an output text field control"),
  QT_TRANSLATE_NOOP("Commands", "Add an output toggle control"),
  QT_TRANSLATE_NOOP("Commands", "Assistant"),
  QT_TRANSLATE_NOOP("Commands", "Audio"),
  QT_TRANSLATE_NOOP("Commands", "Auto Layout"),
  QT_TRANSLATE_NOOP("Commands", "Bar Panel"),
  QT_TRANSLATE_NOOP("Commands", "Bluetooth"),
  QT_TRANSLATE_NOOP("Commands", "Browse and install extensions"),
  QT_TRANSLATE_NOOP("Commands", "Browse documentation, FAQ, and wiki"),
  QT_TRANSLATE_NOOP("Commands", "Browse example projects"),
  QT_TRANSLATE_NOOP("Commands", "Browse, replay, and export recorded sessions"),
  QT_TRANSLATE_NOOP("Commands", "Build an operator app for the current project"),
  QT_TRANSLATE_NOOP("Commands", "Button"),
  QT_TRANSLATE_NOOP("Commands", "CAN Bus"),
  QT_TRANSLATE_NOOP("Commands", "CSV File"),
  QT_TRANSLATE_NOOP("Commands", "Chat with an AI to build and edit your project"),
  QT_TRANSLATE_NOOP("Commands", "Check device permissions, adapters, and host reachability"),
  QT_TRANSLATE_NOOP("Commands", "Clear Console"),
  QT_TRANSLATE_NOOP("Commands", "Clear Window"),
  QT_TRANSLATE_NOOP("Commands", "Clear the console output"),
  QT_TRANSLATE_NOOP("Commands", "Clock"),
  QT_TRANSLATE_NOOP("Commands", "Close"),
  QT_TRANSLATE_NOOP("Commands", "Close Window"),
  QT_TRANSLATE_NOOP("Commands", "Close session file"),
  QT_TRANSLATE_NOOP("Commands", "Collapse All"),
  QT_TRANSLATE_NOOP("Commands", "Collapse Duplicates"),
  QT_TRANSLATE_NOOP("Commands", "Collapse repeated console lines"),
  QT_TRANSLATE_NOOP("Commands", "Collapse the project tree to its overview"),
  QT_TRANSLATE_NOOP("Commands", "Command Palette"),
  QT_TRANSLATE_NOOP("Commands", "Compass"),
  QT_TRANSLATE_NOOP("Commands", "Connect"),
  QT_TRANSLATE_NOOP("Commands", "Connect or disconnect from the configured device"),
  QT_TRANSLATE_NOOP("Commands", "Connection Diagnostics"),
  QT_TRANSLATE_NOOP("Commands", "Console"),
  QT_TRANSLATE_NOOP("Commands", "Console Echo"),
  QT_TRANSLATE_NOOP("Commands", "Console Only Mode"),
  QT_TRANSLATE_NOOP("Commands", "Console Timestamps"),
  QT_TRANSLATE_NOOP("Commands", "Console Transcript"),
  QT_TRANSLATE_NOOP("Commands", "Create a new JSON project"),
  QT_TRANSLATE_NOOP("Commands", "Dataset"),
  QT_TRANSLATE_NOOP("Commands", "Delete"),
  QT_TRANSLATE_NOOP("Commands", "Delete the selected session"),
  QT_TRANSLATE_NOOP("Commands", "Deploy"),
  QT_TRANSLATE_NOOP("Commands", "Deploy Operator App"),
  QT_TRANSLATE_NOOP("Commands", "Disconnect"),
  QT_TRANSLATE_NOOP("Commands", "Echo transmitted data in the console"),
  QT_TRANSLATE_NOOP("Commands", "Examples"),
  QT_TRANSLATE_NOOP("Commands", "Expand All"),
  QT_TRANSLATE_NOOP("Commands", "Expand every item in the project tree"),
  QT_TRANSLATE_NOOP("Commands", "Export"),
  QT_TRANSLATE_NOOP("Commands", "Export CSV"),
  QT_TRANSLATE_NOOP("Commands", "Export PDF"),
  QT_TRANSLATE_NOOP("Commands", "Export selected session to CSV"),
  QT_TRANSLATE_NOOP("Commands", "Extensions"),
  QT_TRANSLATE_NOOP("Commands", "FFT Plot"),
  QT_TRANSLATE_NOOP("Commands", "File Transmission"),
  QT_TRANSLATE_NOOP("Commands", "Freeze Dashboard"),
  QT_TRANSLATE_NOOP("Commands", "Full Screen"),
  QT_TRANSLATE_NOOP("Commands", "GPS Map"),
  QT_TRANSLATE_NOOP("Commands", "Gauge"),
  QT_TRANSLATE_NOOP("Commands", "Generate a PDF report for the selected session"),
  QT_TRANSLATE_NOOP("Commands", "Generate a project from a Protocol Buffers (.proto) schema"),
  QT_TRANSLATE_NOOP("Commands", "Group"),
  QT_TRANSLATE_NOOP("Commands", "Gyroscope"),
  QT_TRANSLATE_NOOP("Commands", "HID"),
  QT_TRANSLATE_NOOP("Commands", "Help Center"),
  QT_TRANSLATE_NOOP("Commands", "Hex Display"),
  QT_TRANSLATE_NOOP("Commands", "Image"),
  QT_TRANSLATE_NOOP("Commands", "Import Protobuf Schema"),
  QT_TRANSLATE_NOOP("Commands", "Knob"),
  QT_TRANSLATE_NOOP("Commands", "LED Indicator"),
  QT_TRANSLATE_NOOP("Commands", "Level Indicator"),
  QT_TRANSLATE_NOOP("Commands", "License Management"),
  QT_TRANSLATE_NOOP("Commands", "Lock"),
  QT_TRANSLATE_NOOP("Commands", "Lock Project Editor"),
  QT_TRANSLATE_NOOP("Commands", "MDF4 File"),
  QT_TRANSLATE_NOOP("Commands", "Macros"),
  QT_TRANSLATE_NOOP("Commands", "Manage your Serial Studio Pro license"),
  QT_TRANSLATE_NOOP("Commands", "Minimize Window"),
  QT_TRANSLATE_NOOP("Commands", "Modbus"),
  QT_TRANSLATE_NOOP("Commands", "Multi-Plot"),
  QT_TRANSLATE_NOOP("Commands", "Navigate Back"),
  QT_TRANSLATE_NOOP("Commands", "Navigate Forward"),
  QT_TRANSLATE_NOOP("Commands", "Network"),
  QT_TRANSLATE_NOOP("Commands", "New"),
  QT_TRANSLATE_NOOP("Commands", "New Project"),
  QT_TRANSLATE_NOOP("Commands", "Next Workspace"),
  QT_TRANSLATE_NOOP("Commands", "Notifications"),
  QT_TRANSLATE_NOOP("Commands", "Open"),
  QT_TRANSLATE_NOOP("Commands", "Open CSV"),
  QT_TRANSLATE_NOOP("Commands", "Open MDF4"),
  QT_TRANSLATE_NOOP("Commands", "Open Project"),
  QT_TRANSLATE_NOOP("Commands", "Open a session file"),
  QT_TRANSLATE_NOOP("Commands", "Open an existing JSON project"),
  QT_TRANSLATE_NOOP("Commands", "Open application settings and preferences"),
  QT_TRANSLATE_NOOP("Commands", "Open the Assistant"),
  QT_TRANSLATE_NOOP("Commands", "Open the Project Editor documentation"),
  QT_TRANSLATE_NOOP("Commands", "Open the Project Editor to create or modify your JSON layout"),
  QT_TRANSLATE_NOOP("Commands", "Output"),
  QT_TRANSLATE_NOOP("Commands", "Painter"),
  QT_TRANSLATE_NOOP("Commands", "Pause"),
  QT_TRANSLATE_NOOP("Commands", "Play a CSV file as if it were live sensor data"),
  QT_TRANSLATE_NOOP("Commands", "Play an MDF4 file as if it were live sensor data (Pro)"),
  QT_TRANSLATE_NOOP("Commands", "Plot"),
  QT_TRANSLATE_NOOP("Commands", "Preferences"),
  QT_TRANSLATE_NOOP("Commands", "Previous Workspace"),
  QT_TRANSLATE_NOOP("Commands", "Problem Center"),
  QT_TRANSLATE_NOOP("Commands", "Process"),
  QT_TRANSLATE_NOOP("Commands", "Project Editor"),
  QT_TRANSLATE_NOOP("Commands", "Project File Mode"),
  QT_TRANSLATE_NOOP("Commands", "Protobuf"),
  QT_TRANSLATE_NOOP("Commands", "Quick Plot Mode"),
  QT_TRANSLATE_NOOP("Commands", "Quit"),
  QT_TRANSLATE_NOOP("Commands", "Redo"),
  QT_TRANSLATE_NOOP("Commands", "Redo the last undone project edit"),
  QT_TRANSLATE_NOOP("Commands", "Remote Dashboard"),
  QT_TRANSLATE_NOOP("Commands", "Replay"),
  QT_TRANSLATE_NOOP("Commands", "Replay selected session on the dashboard"),
  QT_TRANSLATE_NOOP("Commands", "Reset"),
  QT_TRANSLATE_NOOP("Commands", "Restore"),
  QT_TRANSLATE_NOOP("Commands", "Restore Backup"),
  QT_TRANSLATE_NOOP("Commands", "Restore Project"),
  QT_TRANSLATE_NOOP("Commands", "Restore a recent automatic snapshot of the current project"),
  QT_TRANSLATE_NOOP("Commands", "Restore the project file from this session file"),
  QT_TRANSLATE_NOOP("Commands", "Resume"),
  QT_TRANSLATE_NOOP("Commands", "Review project, link, and script diagnostics"),
  QT_TRANSLATE_NOOP("Commands", "Run API commands and script macros interactively"),
  QT_TRANSLATE_NOOP("Commands", "Save"),
  QT_TRANSLATE_NOOP("Commands", "Save As"),
  QT_TRANSLATE_NOOP("Commands", "Save Project"),
  QT_TRANSLATE_NOOP("Commands", "Save Project As"),
  QT_TRANSLATE_NOOP("Commands", "Search"),
  QT_TRANSLATE_NOOP("Commands", "Select Bluetooth Low Energy communication"),
  QT_TRANSLATE_NOOP("Commands", "Select CAN Bus communication (Pro)"),
  QT_TRANSLATE_NOOP("Commands", "Select HID device communication (Pro)"),
  QT_TRANSLATE_NOOP("Commands", "Select MODBUS communication (Pro)"),
  QT_TRANSLATE_NOOP("Commands", "Select Serial port (UART) communication"),
  QT_TRANSLATE_NOOP("Commands", "Select TCP/UDP network communication"),
  QT_TRANSLATE_NOOP("Commands", "Select audio input device (Pro)"),
  QT_TRANSLATE_NOOP("Commands", "Select process pipe communication (Pro)"),
  QT_TRANSLATE_NOOP("Commands", "Select raw USB communication (Pro)"),
  QT_TRANSLATE_NOOP("Commands", "Session Database"),
  QT_TRANSLATE_NOOP("Commands", "Sessions"),
  QT_TRANSLATE_NOOP("Commands", "Set a password and lock the Project Editor"),
  QT_TRANSLATE_NOOP("Commands", "Set a password to prevent session deletions"),
  QT_TRANSLATE_NOOP("Commands", "Show application info and license details"),
  QT_TRANSLATE_NOOP("Commands", "Show timestamps in the console"),
  QT_TRANSLATE_NOOP("Commands", "Slider"),
  QT_TRANSLATE_NOOP("Commands", "Start Menu"),
  QT_TRANSLATE_NOOP("Commands", "Stopwatch"),
  QT_TRANSLATE_NOOP("Commands", "Switch to Console Only mode (no parsing)"),
  QT_TRANSLATE_NOOP("Commands", "Switch to Project File mode (parse via a project)"),
  QT_TRANSLATE_NOOP("Commands", "Switch to Quick Plot mode (comma-separated values)"),
  QT_TRANSLATE_NOOP("Commands", "Table"),
  QT_TRANSLATE_NOOP("Commands", "Text Field"),
  QT_TRANSLATE_NOOP("Commands", "Toggle"),
  QT_TRANSLATE_NOOP("Commands", "Toggle hexadecimal console display"),
  QT_TRANSLATE_NOOP("Commands", "Tools"),
  QT_TRANSLATE_NOOP("Commands", "UART"),
  QT_TRANSLATE_NOOP("Commands", "USB"),
  QT_TRANSLATE_NOOP("Commands", "Undo"),
  QT_TRANSLATE_NOOP("Commands", "Undo the last project edit"),
  QT_TRANSLATE_NOOP("Commands", "Unlock"),
  QT_TRANSLATE_NOOP("Commands", "View detailed documentation and ask questions on DeepWiki"),
  QT_TRANSLATE_NOOP("Commands", "Watch another Serial Studio instance's dashboard over the network"),
  QT_TRANSLATE_NOOP("Commands", "Web View"),
};
// clang-format on
