/*
 * Serial Studio
 * https://serial-studio.com/
 *
 * Copyright (C) 2020-2025 Alex Spataru
 *
 * SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-SerialStudio-Commercial
 */

#ifdef ENABLE_GRPC

#  include "API/GRPC/ProtoGenerator.h"

#  include <cmath>
#  include <QFile>
#  include <QJsonArray>
#  include <QJsonDocument>
#  include <QTextStream>

#  include "API/CommandRegistry.h"
#  include "SerialStudio.h"

//--------------------------------------------------------------------------------------------------
// Public methods
//--------------------------------------------------------------------------------------------------

/**
 * @brief Generates a complete .proto file from CommandRegistry.
 */
QString API::GRPC::ProtoGenerator::generateProto()
{
  QString proto;
  QTextStream out(&proto);

  writeProtoHeader(out);
  writeSharedMessages(out);

  QStringList rpc_lines;
  QStringList message_defs;
  buildCommandMessages(message_defs, rpc_lines);

  writeService(out, message_defs, rpc_lines);
  return proto;
}

/**
 * @brief Writes the proto3 syntax declaration, package, and well-known imports.
 */
void API::GRPC::ProtoGenerator::writeProtoHeader(QTextStream& out)
{
  out << "// Auto-generated by Serial Studio ProtoGenerator\n"
      << "// Do not edit manually -- regenerate from Settings > Export .proto\n"
      << "\n"
      << "syntax = \"proto3\";\n"
      << "\n"
      << "package serialstudio.typed;\n"
      << "\n"
      << "import \"google/protobuf/struct.proto\";\n"
      << "import \"google/protobuf/empty.proto\";\n"
      << "\n";
}

/**
 * @brief Emits the response, streaming, and discovery message definitions shared by every RPC.
 */
void API::GRPC::ProtoGenerator::writeSharedMessages(QTextStream& out)
{
  out << "// Common response used by all command RPCs\n"
      << "message CommandResponse {\n"
      << "  string id = 1;\n"
      << "  bool success = 2;\n"
      << "  google.protobuf.Value result = 3;\n"
      << "  string error_code = 4;\n"
      << "  string error_message = 5;\n"
      << "}\n"
      << "\n";

  out << "// Streaming messages\n"
      << "message StreamRequest {}\n"
      << "\n"
      << "message FrameData {\n"
      << "  int64 timestamp_ms = 1;\n"
      << "  google.protobuf.Struct frame = 2;\n"
      << "}\n"
      << "\n"
      << "message RawData {\n"
      << "  bytes data = 1;\n"
      << "  int64 timestamp_ms = 2;\n"
      << "}\n"
      << "\n"
      << "message RawDataRequest {\n"
      << "  string id = 1;\n"
      << "  bytes data = 2;\n"
      << "}\n"
      << "\n"
      << "message CommandInfo {\n"
      << "  string name = 1;\n"
      << "  string description = 2;\n"
      << "  google.protobuf.Struct input_schema = 3;\n"
      << "}\n"
      << "\n"
      << "message CommandList {\n"
      << "  repeated CommandInfo commands = 1;\n"
      << "}\n"
      << "\n";
}

/**
 * @brief Builds per-command request messages plus the matching RPC lines from CommandRegistry.
 */
void API::GRPC::ProtoGenerator::buildCommandMessages(QStringList& message_defs,
                                                     QStringList& rpc_lines)
{
  static auto& commandRegistry = API::CommandRegistry::instance();
  const auto& commands         = commandRegistry.commands();

  for (auto it = commands.begin(); it != commands.end(); ++it) {
    const auto& def     = it.value();
    const auto rpc_name = sanitizeName(def.name);
    const auto msg_name = rpc_name + "Request";
    const auto entry    = ledger().value(def.name).toObject();

    message_defs.append(buildMessage(msg_name, def.inputSchema, entry));
    rpc_lines.append(QStringLiteral("%1\n  rpc %2(%3) returns (CommandResponse);")
                       .arg(commentBlock(def.description), rpc_name, msg_name));
  }
}

/**
 * @brief Writes per-command request messages and the typed service block with streaming RPCs.
 */
void API::GRPC::ProtoGenerator::writeService(QTextStream& out,
                                             const QStringList& message_defs,
                                             const QStringList& rpc_lines)
{
  out << "// Per-command request messages\n\n";
  for (const auto& msg : std::as_const(message_defs))
    out << msg << "\n";

  out << "\n// Typed service with per-command RPCs\n"
      << "service SerialStudioTypedAPI {\n";

  for (const auto& rpc : std::as_const(rpc_lines))
    out << rpc << "\n\n";

  out << "  // Streaming RPCs\n"
      << "  rpc StreamFrames(StreamRequest) returns (stream FrameData);\n"
      << "  rpc StreamRawData(StreamRequest) returns (stream RawData);\n"
      << "  rpc WriteRawData(RawDataRequest) returns (CommandResponse);\n"
      << "  rpc ListCommands(google.protobuf.Empty) returns (CommandList);\n"
      << "}\n";
}

/**
 * @brief Exports the generated .proto to the specified file path.
 */
bool API::GRPC::ProtoGenerator::exportToFile(const QString& filePath)
{
  if (filePath.isEmpty())
    return false;

  QFile file(filePath);
  if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
    return false;

  QTextStream out(&file);
  out << generateProto();
  return true;
}

//--------------------------------------------------------------------------------------------------
// Private helpers
//--------------------------------------------------------------------------------------------------

/**
 * @brief Returns the bundled gRPC field-number ledger, parsed once. Numbering is append-only
 *        released state: reading it here is what keeps a published field number from moving
 *        when a schema property is inserted ahead of it alphabetically.
 */
const QJsonObject& API::GRPC::ProtoGenerator::ledger()
{
  static const QJsonObject entries = [] {
    QFile file(QStringLiteral(":/api/proto-fields.json"));
    if (!file.open(QIODevice::ReadOnly))
      return QJsonObject();

    const auto document = QJsonDocument::fromJson(file.readAll());
    return document.object().value(QStringLiteral("commands")).toObject();
  }();

  return entries;
}

/**
 * @brief Renders a JSON scalar exactly as the generator script's proto_scalar() does -- backslash
 *        and quote escaped in that order -- so the enum comments of both emitters stay
 *        byte-identical for every input, not just for quote-free vocabularies.
 */
QString API::GRPC::ProtoGenerator::jsonScalar(const QJsonValue& value)
{
  if (value.isString()) {
    auto text = value.toString();
    text.replace(QStringLiteral("\\"), QStringLiteral("\\\\"));
    text.replace(QStringLiteral("\""), QStringLiteral("\\\""));
    return QStringLiteral("\"%1\"").arg(text);
  }

  if (value.isBool())
    return value.toBool() ? QStringLiteral("true") : QStringLiteral("false");

  if (value.isDouble()) {
    const double number = SerialStudio::toDouble(value);
    if (number == std::trunc(number))
      return QString::number(static_cast<qint64>(number));

    return QString::number(number);
  }

  return QStringLiteral("null");
}

/**
 * @brief Folds a multi-line command description into a comment block protoc can parse; an
 *        unprefixed continuation line makes the whole file invalid.
 */
QString API::GRPC::ProtoGenerator::commentBlock(const QString& text)
{
  QString folded = text;
  folded.replace(QStringLiteral("\r\n"), QStringLiteral("\n"));
  folded.replace(QStringLiteral("\n"), QStringLiteral("\n  // "));
  return QStringLiteral("  // ") + folded;
}

/**
 * @brief Renames a parameter that would collide with the fixed 'string id = 1' request field;
 *        the ledger still keys the number by the JSON name.
 */
QString API::GRPC::ProtoGenerator::protoFieldName(const QString& param)
{
  if (param == QStringLiteral("id"))
    return QStringLiteral("id_param");

  return param;
}

/**
 * @brief Builds the trailing comment of one field: its JSON name when renamed, and its enum
 *        domain when the schema declares one.
 */
QString API::GRPC::ProtoGenerator::fieldComment(const QString& param, const QJsonObject& schema)
{
  QStringList parts;
  if (protoFieldName(param) != param)
    parts.append(QStringLiteral("JSON name: %1").arg(param));

  const auto domain = schema.value(QStringLiteral("enum")).toArray();
  if (!domain.isEmpty()) {
    QStringList values;
    for (const auto& value : domain)
      values.append(jsonScalar(value));

    parts.append(QStringLiteral("enum: ") + values.join(QStringLiteral(", ")));
  }

  if (parts.isEmpty())
    return QString();

  return QStringLiteral("  // ") + parts.join(QStringLiteral("; "));
}

/**
 * @brief Maps every schema property to its ledger number, appending fresh numbers after the
 *        message's current maximum for parameters the bundled ledger predates, so a number
 *        already published can never move.
 */
QMap<int, QString> API::GRPC::ProtoGenerator::numberedFields(const QJsonObject& props,
                                                             const QJsonObject& entry)
{
  const auto numbers  = entry.value(QStringLiteral("fields")).toObject();
  const auto reserved = entry.value(QStringLiteral("reserved")).toArray();

  int next = 1;
  for (const auto& value : reserved)
    next = qMax(next, value.toInt());

  for (auto it = numbers.begin(); it != numbers.end(); ++it)
    next = qMax(next, it.value().toInt());

  QMap<int, QString> assigned;
  QStringList pending;
  for (auto it = props.begin(); it != props.end(); ++it) {
    const int number = numbers.value(it.key()).toInt(0);
    if (number > 1)
      assigned.insert(number, it.key());
    else
      pending.append(it.key());
  }

  for (const auto& param : std::as_const(pending))
    assigned.insert(++next, param);

  return assigned;
}

/**
 * @brief Builds one per-command request message: retired numbers as a proto reserved statement,
 *        the fixed request id, then every parameter at its ledger number in ascending order.
 */
QString API::GRPC::ProtoGenerator::buildMessage(const QString& name,
                                                const QJsonObject& schema,
                                                const QJsonObject& entry)
{
  QString msg;
  QTextStream out(&msg);
  out << "message " << name << " {\n";

  const auto reserved = entry.value(QStringLiteral("reserved")).toArray();
  if (!reserved.isEmpty()) {
    QStringList numbers;
    for (const auto& value : reserved)
      numbers.append(QString::number(value.toInt()));

    out << "  reserved " << numbers.join(QStringLiteral(", ")) << ";\n";
  }

  out << "  string id = 1;\n";

  const auto props  = schema.value(QStringLiteral("properties")).toObject();
  const auto fields = numberedFields(props, entry);
  for (auto it = fields.begin(); it != fields.end(); ++it) {
    const auto field_schema = props.value(it.value()).toObject();
    const auto field_type   = jsonTypeToProtoType(field_schema.value("type").toString());
    out << "  " << field_type << " " << protoFieldName(it.value()) << " = " << it.key() << ";"
        << fieldComment(it.value(), field_schema) << "\n";
  }

  out << "}\n";
  return msg;
}

/**
 * @brief Converts a JSON Schema type string to a protobuf type.
 */
QString API::GRPC::ProtoGenerator::jsonTypeToProtoType(const QString& jsonType)
{
  if (jsonType == QStringLiteral("string"))
    return QStringLiteral("string");

  if (jsonType == QStringLiteral("number"))
    return QStringLiteral("double");

  if (jsonType == QStringLiteral("integer"))
    return QStringLiteral("int64");

  if (jsonType == QStringLiteral("boolean"))
    return QStringLiteral("bool");

  if (jsonType == QStringLiteral("array"))
    return QStringLiteral("google.protobuf.ListValue");

  return QStringLiteral("google.protobuf.Struct");
}

/**
 * @brief Sanitizes a dot-notation command name to a valid protobuf identifier.
 */
QString API::GRPC::ProtoGenerator::sanitizeName(const QString& name)
{
  QString result;
  bool capitalize = true;

  for (const auto& ch : name) {
    if (ch == '.' || ch == '_' || ch == '-') {
      capitalize = true;
      continue;
    }

    if (capitalize) {
      result     += ch.toUpper();
      capitalize  = false;
    } else {
      result += ch;
    }
  }

  return result;
}

#endif  // ENABLE_GRPC
