/*
 * Serial Studio
 * https://serial-studio.com/
 *
 * Copyright (C) 2020-2025 Alex Spataru
 *
 * SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-SerialStudio-Commercial
 */

#ifdef ENABLE_GRPC

#  include "API/GRPC/ProtoGenerator.h"

#  include <QFile>
#  include <QJsonArray>
#  include <QTextStream>

#  include "API/CommandRegistry.h"

//--------------------------------------------------------------------------------------------------
// Public methods
//--------------------------------------------------------------------------------------------------

/**
 * @brief Generates a complete .proto file from CommandRegistry.
 *
 * Produces a protobuf service definition with:
 * - Per-command typed request messages derived from JSON Schema
 * - A unified response type using google.protobuf.Value
 * - Generic streaming RPCs for frames and raw data
 * - ListCommands discovery RPC
 */
QString API::GRPC::ProtoGenerator::generateProto()
{
  // Initialize output stream
  QString proto;
  QTextStream out(&proto);

  // Header
  out << "// Auto-generated by Serial Studio ProtoGenerator\n"
      << "// Do not edit manually — regenerate from Settings > Export .proto\n"
      << "\n"
      << "syntax = \"proto3\";\n"
      << "\n"
      << "package serialstudio.typed;\n"
      << "\n"
      << "import \"google/protobuf/struct.proto\";\n"
      << "import \"google/protobuf/empty.proto\";\n"
      << "\n";

  // Common response type
  out << "// Common response used by all command RPCs\n"
      << "message CommandResponse {\n"
      << "  string id = 1;\n"
      << "  bool success = 2;\n"
      << "  google.protobuf.Value result = 3;\n"
      << "  string error_code = 4;\n"
      << "  string error_message = 5;\n"
      << "}\n"
      << "\n";

  // Streaming messages
  out << "// Streaming messages\n"
      << "message StreamRequest {}\n"
      << "\n"
      << "message FrameData {\n"
      << "  int64 timestamp_ms = 1;\n"
      << "  google.protobuf.Struct frame = 2;\n"
      << "}\n"
      << "\n"
      << "message RawData {\n"
      << "  bytes data = 1;\n"
      << "  int64 timestamp_ms = 2;\n"
      << "}\n"
      << "\n"
      << "message RawDataRequest {\n"
      << "  string id = 1;\n"
      << "  bytes data = 2;\n"
      << "}\n"
      << "\n"
      << "message CommandInfo {\n"
      << "  string name = 1;\n"
      << "  string description = 2;\n"
      << "  google.protobuf.Struct input_schema = 3;\n"
      << "}\n"
      << "\n"
      << "message CommandList {\n"
      << "  repeated CommandInfo commands = 1;\n"
      << "}\n"
      << "\n";

  // Generate per-command request messages and collect RPC lines
  const auto& commands = API::CommandRegistry::instance().commands();
  QStringList rpc_lines;
  QStringList message_defs;

  for (auto it = commands.begin(); it != commands.end(); ++it) {
    const auto& def     = it.value();
    const auto msg_name = sanitizeName(def.name) + "Request";

    // Build request message from JSON Schema
    QString msg;
    QTextStream msg_out(&msg);
    msg_out << "message " << msg_name << " {\n"
            << "  string id = 1;\n";

    if (!def.inputSchema.isEmpty()) {
      const auto props = def.inputSchema.value("properties").toObject();
      int field_num    = 2;

      for (auto pit = props.begin(); pit != props.end(); ++pit) {
        const auto field_schema = pit.value().toObject();
        const auto field_type   = jsonTypeToProtoType(field_schema.value("type").toString());
        const auto field_name   = pit.key();

        msg_out << "  " << field_type << " " << field_name << " = " << field_num++ << ";\n";
      }
    }

    msg_out << "}\n";
    message_defs.append(msg);

    // RPC line
    const auto rpc_name = sanitizeName(def.name);
    rpc_lines.append(QStringLiteral("  // %1\n  rpc %2(%3) returns (CommandResponse);")
                       .arg(def.description, rpc_name, msg_name));
  }

  // Write all request messages
  out << "// Per-command request messages\n\n";
  for (const auto& msg : std::as_const(message_defs))
    out << msg << "\n";

  // Write service definition
  out << "\n// Typed service with per-command RPCs\n"
      << "service SerialStudioTypedAPI {\n";

  for (const auto& rpc : std::as_const(rpc_lines))
    out << rpc << "\n\n";

  // Generic RPCs
  out << "  // Streaming RPCs\n"
      << "  rpc StreamFrames(StreamRequest) returns (stream FrameData);\n"
      << "  rpc StreamRawData(StreamRequest) returns (stream RawData);\n"
      << "  rpc WriteRawData(RawDataRequest) returns (CommandResponse);\n"
      << "  rpc ListCommands(google.protobuf.Empty) returns (CommandList);\n"
      << "}\n";

  return proto;
}

/**
 * @brief Exports the generated .proto to the specified file path.
 */
bool API::GRPC::ProtoGenerator::exportToFile(const QString& filePath)
{
  // Validate file path
  if (filePath.isEmpty())
    return false;

  QFile file(filePath);
  if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
    return false;

  QTextStream out(&file);
  out << generateProto();
  return true;
}

//--------------------------------------------------------------------------------------------------
// Private helpers
//--------------------------------------------------------------------------------------------------

/**
 * @brief Converts a JSON Schema type string to a protobuf type.
 */
QString API::GRPC::ProtoGenerator::jsonTypeToProtoType(const QString& jsonType)
{
  // Map JSON Schema type to protobuf field type
  if (jsonType == QStringLiteral("string"))
    return QStringLiteral("string");
  if (jsonType == QStringLiteral("number"))
    return QStringLiteral("double");
  if (jsonType == QStringLiteral("integer"))
    return QStringLiteral("int64");
  if (jsonType == QStringLiteral("boolean"))
    return QStringLiteral("bool");
  if (jsonType == QStringLiteral("array"))
    return QStringLiteral("google.protobuf.ListValue");

  // object, mixed, or unknown → use Struct
  return QStringLiteral("google.protobuf.Struct");
}

/**
 * @brief Sanitizes a dot-notation command name to a valid protobuf identifier.
 *
 * Converts "io.driver.uart.setBaudRate" to "IoDriverUartSetBaudRate".
 */
QString API::GRPC::ProtoGenerator::sanitizeName(const QString& name)
{
  // Convert dot-notation to CamelCase
  QString result;
  bool capitalize = true;

  for (const auto& ch : name) {
    if (ch == '.' || ch == '_' || ch == '-') {
      capitalize = true;
      continue;
    }

    if (capitalize) {
      result += ch.toUpper();
      capitalize = false;
    } else {
      result += ch;
    }
  }

  return result;
}

#endif  // ENABLE_GRPC
