#!/usr/bin/env python3
"""
Protobuf Sensor Simulator
=========================

Streams binary-encoded protobuf frames over UDP for the project generated by
Serial Studio's `.proto` importer. The auto-detect parser scores each frame
against every top-level message, so this simulator alternates between two
message shapes:

  - Sensor : the full telemetry frame (temperature, humidity, status, note,
             plus embedded `accel` and `gyro` sub-messages)
  - Vec3   : a bare 3-axis vector, sent occasionally so the top-level Vec3
             group on the dashboard also lights up

Wire format is hand-rolled with `struct`; no `protobuf` Python package is
needed.

Default target: udp://127.0.0.1:7878. Configure Serial Studio with:
  - Source -> Network -> UDP Listener on port 7878
  - Decoder: Binary, Frame detection: No delimiters
  (Or just open the generated project file.)

Usage: python sensor_simulator.py
"""

import sys

# Force UTF-8 console output: Windows defaults to cp1252, which cannot encode
# the Unicode characters this script prints (e.g. arrows / check marks).
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass

import math
import random
import socket
import struct
import time

HOST = "127.0.0.1"
PORT = 7878
RATE_HZ = 25.0
VEC3_EVERY_N_FRAMES = 5  # one bare Vec3 frame for every N total frames


# ---------------------------------------------------------------------------
# Wire-format helpers
# ---------------------------------------------------------------------------


def varint(n: int) -> bytes:
    """Encode an unsigned integer as a protobuf varint."""
    out = bytearray()
    while True:
        b = n & 0x7F
        n >>= 7
        if n:
            out.append(b | 0x80)
        else:
            out.append(b)
            return bytes(out)


def tag(field: int, wire: int) -> bytes:
    return varint((field << 3) | wire)


def field_uint(field: int, value: int) -> bytes:
    return tag(field, 0) + varint(value)


def field_float(field: int, value: float) -> bytes:
    return tag(field, 5) + struct.pack("<f", value)


def field_string(field: int, value: str) -> bytes:
    payload = value.encode("utf-8")
    return tag(field, 2) + varint(len(payload)) + payload


def field_submsg(field: int, payload: bytes) -> bytes:
    return tag(field, 2) + varint(len(payload)) + payload


def encode_vec3(x: float, y: float, z: float) -> bytes:
    return field_float(1, x) + field_float(2, y) + field_float(3, z)


# ---------------------------------------------------------------------------
# Frame builders
# ---------------------------------------------------------------------------


def make_sensor_frame(t: float, counter: int) -> bytes:
    """Build a Sensor frame with values that look interesting on a -100..100 plot."""
    # Slow + medium + jitter blend so the lines look alive, not robotic.
    temperature = 25.0 + 40.0 * math.sin(t * 0.7) + 5.0 * math.sin(t * 4.3)
    humidity = 50.0 + 35.0 * math.sin(t * 0.31 + 1.0) + random.uniform(-2.0, 2.0)
    # 3-axis accel: chunky vibration + DC offset on Z (1g-ish, scaled up for plots).
    ax = 35.0 * math.sin(t * 5.0) + 8.0 * math.sin(t * 23.0)
    ay = 35.0 * math.cos(t * 5.0) + 8.0 * math.cos(t * 19.0)
    az = 20.0 + 12.0 * math.sin(t * 7.0)
    # 3-axis gyro: phase-shifted rotations.
    gx = 70.0 * math.sin(t * 1.3)
    gy = 70.0 * math.cos(t * 1.3 + 0.7)
    gz = 50.0 * math.sin(t * 0.6)
    # Status: bitfield reflecting current thresholds (T > 40, H > 70, motion).
    status = 0
    if temperature > 40.0:
        status |= 0x01
    if humidity > 70.0:
        status |= 0x02
    if abs(ax) > 30.0 or abs(ay) > 30.0:
        status |= 0x04
    if abs(gz) > 30.0:
        status |= 0x08

    note = f"Sensor #{counter}"

    out = bytearray()
    out += field_float(1, temperature)
    out += field_float(2, humidity)
    out += field_submsg(3, encode_vec3(ax, ay, az))  # accel
    out += field_submsg(4, encode_vec3(gx, gy, gz))  # gyro
    out += field_uint(5, status)
    out += field_string(6, note)
    return bytes(out)


def make_vec3_frame(t: float, counter: int) -> bytes:
    """Build a bare Vec3 frame (e.g. an independent magnetometer reading)."""
    x = 60.0 * math.sin(t * 0.5 + 2.1)
    y = 60.0 * math.cos(t * 0.5 + 2.1)
    z = 40.0 * math.sin(t * 0.25)
    return encode_vec3(x, y, z)


# ---------------------------------------------------------------------------
# Live status line
# ---------------------------------------------------------------------------

ANSI_CLEAR_EOL = "\033[K"


def render_status(
    elapsed: float, total: int, sensor_count: int, vec3_count: int, kind: str, size: int
) -> str:
    rate = total / elapsed if elapsed > 0 else 0.0
    return (
        f"  {kind:<6}  {size:3d}B  "
        f"|  sent {total:>6}  ({sensor_count} sensor + {vec3_count} vec3)  "
        f"|  {rate:5.1f} Hz  |  {elapsed:6.1f}s"
        f"{ANSI_CLEAR_EOL}\r"
    )


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------


def main() -> None:
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    period = 1.0 / RATE_HZ

    sys.stdout.write(
        f"\nProtobuf Sensor Simulator\n"
        f"  target  : udp://{HOST}:{PORT}\n"
        f"  rate    : {RATE_HZ:.0f} Hz\n"
        f"  mix     : Sensor (default) + bare Vec3 every {VEC3_EVERY_N_FRAMES} frames\n"
        f"  stop    : Ctrl+C\n\n"
    )
    sys.stdout.flush()

    t0 = time.monotonic()
    counter = 0
    sensor_count = 0
    vec3_count = 0
    next_t = t0

    try:
        while True:
            t = time.monotonic() - t0
            counter += 1

            if counter % VEC3_EVERY_N_FRAMES == 0:
                frame = make_vec3_frame(t, counter)
                kind = "Vec3"
                vec3_count += 1
            else:
                frame = make_sensor_frame(t, counter)
                kind = "Sensor"
                sensor_count += 1

            sock.sendto(frame, (HOST, PORT))

            # Throttle.
            next_t += period
            sleep_for = next_t - time.monotonic()
            if sleep_for > 0:
                time.sleep(sleep_for)
            elif sleep_for < -0.5:
                next_t = time.monotonic()  # we fell badly behind, resync

            # Status line (refreshes in place).
            sys.stdout.write(
                render_status(t, counter, sensor_count, vec3_count, kind, len(frame))
            )
            sys.stdout.flush()

    finally:
        sys.stdout.write("\n\nstopped.\n")
        sys.stdout.flush()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
