#!/usr/bin/env python3
"""Generate the legacy icon-path map from the spec-0028 migration manifest.

User project files persist workspace icons as qrc URLs; files written before the
icon-tree migration reference pre-migration paths. This script converts
doc/claude/specs/0028-icon-registry/icon-map.csv into
app/src/Misc/IconRegistryLegacy.cpp, a lookup Misc::legacyIconPath() consults so
those saved URLs keep resolving after the qrc compat aliases were dropped (task
T21). Deterministic; rerun only if the manifest ever changes.

Usage:
    python3 scripts/generate-legacy-icons.py
"""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV = ROOT / "doc" / "claude" / "specs" / "0028-icon-registry" / "icon-map.csv"
OUTPUT = ROOT / "app" / "src" / "Misc" / "IconRegistryLegacy.cpp"

HEADER = """/*
 * Serial Studio
 * https://serial-studio.com/
 *
 * Copyright (C) 2020-2026 Alex Spataru
 *
 * This file is dual-licensed:
 *
 * - Under the GNU GPLv3 (or later) for builds that exclude Pro modules.
 * - Under the Serial Studio Commercial License for builds that include
 *   any Pro functionality.
 *
 * You must comply with the terms of one of these licenses, depending
 * on your use case.
 *
 * For GPL terms, see <https://www.gnu.org/licenses/gpl-3.0.html>
 * For commercial terms, see LICENSES/LicenseRef-SerialStudio-Commercial.txt.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-SerialStudio-Commercial
 */

// AUTO-GENERATED by scripts/generate-legacy-icons.py from icon-map.csv; never edit by hand.

#include "Misc/IconRegistryLegacy.h"

#include <QHash>

// clang-format off
static const QHash<QString, QString> kLegacyIcons = {
"""

FOOTER = """};
// clang-format on

/**
 * @brief Maps a pre-migration "qrc:/icons/..." URL persisted in user project
 *        files to its post-migration location; unknown inputs return @p icon
 *        unchanged.
 */
QString Misc::legacyIconPath(const QString& icon)
{
  return kLegacyIcons.value(icon, icon);
}
"""


def main() -> int:
    rows = list(csv.DictReader(CSV.open(encoding="utf-8")))
    lines = [HEADER]
    for row in sorted(rows, key=lambda r: r["old_path"]):
        old = "qrc:/" + row["old_path"]
        new = "qrc:/" + row["target_path"]
        lines.append(f'  {{QStringLiteral("{old}"), QStringLiteral("{new}")}},\n')
    lines.append(FOOTER)
    OUTPUT.write_text("".join(lines), encoding="utf-8", newline="")
    print(
        f"generate-legacy-icons: wrote {OUTPUT.relative_to(ROOT).as_posix()} ({len(rows)} entries)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
