#!/usr/bin/env python3
"""
Generate the SerialStudio.js / SerialStudio.lua scripting SDKs.

Reads the API command registry snapshot (api-schema.json) and emits natural,
namespaced wrapper functions over the raw apiCall(method, params) gateway, so
end users write:

    io.ble.writeCharacteristic("fff1", "5600030C", SerialStudio.Hex)

instead of:

    apiCall("io.ble.writeCharacteristic",
            { characteristicUuid: "fff1", data: "<base64>" })

Inputs:
    app/rcc/api/api-schema.json   (refresh with: SerialStudio --dump-api-schema <path>)

Outputs:
    app/rcc/api/SerialStudio.js
    app/rcc/api/SerialStudio.lua

The outputs are committed and bundled as Qt resources; both are evaluated into
every script engine right after apiCall is installed (see ScriptApiCall).

This script is CWD-independent and writes LF line endings on every platform.
"""

import json
import re
import sys
from pathlib import Path

SCRIPT = Path(__file__).resolve()
ROOT = SCRIPT.parent.parent
API_DIR = ROOT / "app" / "rcc" / "api"
SCHEMA = API_DIR / "api-schema.json"
OUT_DIR = API_DIR
OUT_JS = OUT_DIR / "SerialStudio.js"
OUT_LUA = OUT_DIR / "SerialStudio.lua"
OUT_SYMBOLS = OUT_DIR / "sdk-symbols.json"
PRELUDE_JS = API_DIR / "prelude.js"
PRELUDE_LUA = API_DIR / "prelude.lua"


def read_prelude(path):
    """Return the hand-maintained prelude fragment, or empty if absent."""
    return path.read_text(encoding="utf-8").rstrip() + "\n" if path.exists() else ""


# Param names that carry a binary payload the API expects as base64. A wrapper
# argument for one of these gets a trailing encoding argument (SerialStudio.Hex
# / .Base64 / .Text) so users pass hex or text and never touch base64 directly.
BYTE_PARAMS = {"data", "payload", "bytes"}


def is_byte_param(name, prop):
    """True when a string param should accept an encoding-tagged payload."""
    if name not in BYTE_PARAMS:
        return False
    return prop.get("type", "string") == "string"


def ordered_params(cmd):
    """Return (required_names, optional_names) in a stable order."""
    props = cmd.get("properties", {})
    required = [p for p in cmd.get("required", []) if p in props]
    optional = sorted(n for n in props if n not in required)
    return required, optional


def js_ident(name):
    """A JS-safe local variable name for a parameter."""
    return name


# --------------------------------------------------------------------------
# JavaScript emitter
# --------------------------------------------------------------------------


def emit_js(commands):
    lines = []
    lines.append("// AUTO-GENERATED by scripts/generate-sdk.py. Do not edit by hand.")
    lines.append(
        "// Natural wrappers over apiCall(method, params). Refresh with sanitize-commit."
    )
    lines.append("")
    lines.append("var SerialStudio = {")
    lines.append("  Base64: 0,")
    lines.append("  Hex: 1,")
    lines.append("  Text: 2,")
    lines.append("")
    lines.append("  _encode: function(value, encoding) {")
    lines.append("    if (encoding === SerialStudio.Hex) {")
    lines.append("      var hex = String(value).replace(/[^0-9a-fA-F]/g, '');")
    lines.append("      var bin = '';")
    lines.append("      for (var i = 0; i < hex.length; i += 2)")
    lines.append("        bin += String.fromCharCode(parseInt(hex.substr(i, 2), 16));")
    lines.append("      return btoa(bin);")
    lines.append("    }")
    lines.append("    if (encoding === SerialStudio.Text) {")
    lines.append("      var s = String(value), out = '';")
    lines.append("      for (var j = 0; j < s.length; ++j)")
    lines.append("        out += String.fromCharCode(s.charCodeAt(j) & 0xff);")
    lines.append("      return btoa(out);")
    lines.append("    }")
    lines.append("    return value;  // already base64")
    lines.append("  }")
    lines.append("};")
    lines.append("")
    lines.append(
        "// Core gateway. The host installs the bridge object as __ss_bridge; every"
    )
    lines.append(
        "// wrapper below routes through apiCall. delay() exists only where the host"
    )
    lines.append("// bridge provides it (the control script's worker thread).")
    lines.append(
        "function apiCall(method, params) { return __ss_bridge.call(method, params || {}); }"
    )
    lines.append(
        "function apiCallList()           { return __ss_bridge.listCommands(); }"
    )
    lines.append(
        "function delay(ms)               { if (__ss_bridge.delay) __ss_bridge.delay(ms); }"
    )
    lines.append("")

    # Hand-maintained bridge glue (tableGet, dashboard control, deviceWrite, ...).
    prelude = read_prelude(PRELUDE_JS)
    if prelude:
        lines.append(prelude.rstrip())
        lines.append("")

    # Build the namespace tree so io.ble.* works. Top-level namespaces reuse any
    # existing global of the same name (e.g. the built-in `console`) so we extend
    # it with our methods instead of shadowing it.
    namespaces = set()
    for cmd in commands:
        parts = cmd["name"].split(".")
        for i in range(1, len(parts)):
            namespaces.add(".".join(parts[:i]))
    for ns in sorted(namespaces):
        if "." in ns:
            lines.append("%s = %s || {};" % (ns, ns))
        else:
            lines.append(
                "var %s = (typeof %s !== 'undefined') ? %s : {};" % (ns, ns, ns)
            )
    lines.append("")

    for cmd in commands:
        required, optional = ordered_params(cmd)
        props = cmd.get("properties", {})

        args = []
        body_params = []
        for name in required:
            args.append(js_ident(name))
            if is_byte_param(name, props[name]):
                args.append(name + "Encoding")
                body_params.append((name, name + "Encoding"))
            else:
                body_params.append((name, None))

        opt_arg = "options" if optional else None
        if opt_arg:
            args.append(opt_arg)

        sig = ", ".join(args)
        lines.append("%s = function(%s) {" % (cmd["name"], sig))
        lines.append("  var p = {};")
        for name, enc in body_params:
            if enc:
                lines.append(
                    "  p['%s'] = SerialStudio._encode(%s, %s);" % (name, name, enc)
                )
            else:
                lines.append("  p['%s'] = %s;" % (name, name))
        if opt_arg:
            lines.append(
                "  if (%s) for (var k in %s) p[k] = %s[k];"
                % (opt_arg, opt_arg, opt_arg)
            )
        lines.append("  return apiCall('%s', p);" % cmd["name"])
        lines.append("};")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# --------------------------------------------------------------------------
# Lua emitter
# --------------------------------------------------------------------------


def emit_lua(commands):
    lines = []
    lines.append("-- AUTO-GENERATED by scripts/generate-sdk.py. Do not edit by hand.")
    lines.append(
        "-- Natural wrappers over apiCall(method, params). Refresh with sanitize-commit."
    )
    lines.append("--")
    lines.append(
        "-- apiCall/apiCallList are installed natively by the host (they capture the"
    )
    lines.append(
        "-- per-source id in a C closure, so they cannot be pure Lua). Everything else"
    )
    lines.append("-- in the Serial Studio scripting surface is defined below.")
    lines.append("")
    lines.append("SerialStudio = { Base64 = 0, Hex = 1, Text = 2 }")
    lines.append("")
    lines.append(
        "local _b64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'"
    )
    lines.append("")
    lines.append(
        "-- Encodes a raw byte string as base64 (pure Lua, no host dependency)."
    )
    lines.append("local function _toBase64(bytes)")
    lines.append("  local out, n = {}, #bytes")
    lines.append("  for i = 1, n, 3 do")
    lines.append("    local b1 = bytes:byte(i) or 0")
    lines.append("    local b2 = bytes:byte(i + 1)")
    lines.append("    local b3 = bytes:byte(i + 2)")
    lines.append("    local n1 = b1 >> 2")
    lines.append("    local n2 = ((b1 & 3) << 4) | ((b2 or 0) >> 4)")
    lines.append("    local n3 = ((((b2 or 0) & 15) << 2) | ((b3 or 0) >> 6))")
    lines.append("    local n4 = (b3 or 0) & 63")
    lines.append("    out[#out + 1] = _b64:sub(n1 + 1, n1 + 1)")
    lines.append("    out[#out + 1] = _b64:sub(n2 + 1, n2 + 1)")
    lines.append("    out[#out + 1] = b2 and _b64:sub(n3 + 1, n3 + 1) or '='")
    lines.append("    out[#out + 1] = b3 and _b64:sub(n4 + 1, n4 + 1) or '='")
    lines.append("  end")
    lines.append("  return table.concat(out)")
    lines.append("end")
    lines.append("")
    lines.append("function SerialStudio._encode(value, encoding)")
    lines.append("  if encoding == SerialStudio.Hex then")
    lines.append("    local hex = tostring(value):gsub('%X', '')")
    lines.append("    local bin = {}")
    lines.append("    for i = 1, #hex, 2 do")
    lines.append(
        "      bin[#bin + 1] = string.char(tonumber(hex:sub(i, i + 1), 16) or 0)"
    )
    lines.append("    end")
    lines.append("    return _toBase64(table.concat(bin))")
    lines.append("  elseif encoding == SerialStudio.Text then")
    lines.append("    return _toBase64(tostring(value))")
    lines.append("  end")
    lines.append("  return value")
    lines.append("end")
    lines.append("")

    prelude = read_prelude(PRELUDE_LUA)
    if prelude:
        lines.append(prelude.rstrip())
        lines.append("")

    namespaces = set()
    for cmd in commands:
        parts = cmd["name"].split(".")
        for i in range(1, len(parts)):
            namespaces.add(".".join(parts[:i]))
    for ns in sorted(namespaces):
        if "." in ns:
            lines.append("%s = %s or {}" % (ns, ns))
        else:
            lines.append("%s = %s or {}" % (ns, ns))
    lines.append("")

    for cmd in commands:
        required, optional = ordered_params(cmd)
        props = cmd.get("properties", {})

        args = []
        body_params = []
        for name in required:
            args.append(name)
            if is_byte_param(name, props[name]):
                args.append(name + "_encoding")
                body_params.append((name, name + "_encoding"))
            else:
                body_params.append((name, None))
        opt_arg = "options" if optional else None
        if opt_arg:
            args.append(opt_arg)

        sig = ", ".join(args)
        lines.append("function %s(%s)" % (cmd["name"], sig))
        lines.append("  local p = {}")
        for name, enc in body_params:
            if enc:
                lines.append(
                    "  p['%s'] = SerialStudio._encode(%s, %s)" % (name, name, enc)
                )
            else:
                lines.append("  p['%s'] = %s" % (name, name))
        if opt_arg:
            lines.append(
                "  if %s then for k, v in pairs(%s) do p[k] = v end end"
                % (opt_arg, opt_arg)
            )
        lines.append("  return apiCall('%s', p)" % cmd["name"])
        lines.append("end")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def drop_namespace_collisions(commands):
    """Drop any command whose name is also a namespace prefix of another.

    e.g. a command "io" cannot coexist with "io.connect": the wrapper for "io"
    would overwrite the namespace object. These are rare/accidental; skip them
    and warn rather than emit broken code.
    """
    names = {c["name"] for c in commands}
    prefixes = set()
    for name in names:
        parts = name.split(".")
        for i in range(1, len(parts)):
            prefixes.add(".".join(parts[:i]))

    kept, dropped = [], []
    for cmd in commands:
        if cmd["name"] in prefixes:
            dropped.append(cmd["name"])
        else:
            kept.append(cmd)

    for name in dropped:
        print(
            "[sdk] skipping '%s' (name collides with a namespace)" % name,
            file=sys.stderr,
        )
    return kept


def collect_symbols(commands):
    """Every name a code-editor completer should offer: commands, namespaces,
    the SerialStudio enum, the apiCall/delay bootstrap, and prelude globals."""
    symbols = set()

    # Command names, their namespace prefixes (io, io.ble, ...), and the bare
    # leaf name. The code editor completes on the word under the cursor, which
    # stops at '.', so the leaf (writeCharacteristic) is what actually matches
    # mid-path; the full dotted name and prefixes drive top-level completion.
    for cmd in commands:
        symbols.add(cmd["name"])
        parts = cmd["name"].split(".")
        symbols.add(parts[-1])
        for i in range(1, len(parts)):
            symbols.add(".".join(parts[:i]))

    # SDK constants + core gateway.
    symbols.update(
        [
            "SerialStudio",
            "SerialStudio.Base64",
            "SerialStudio.Hex",
            "SerialStudio.Text",
            "apiCall",
            "apiCallList",
            "delay",
        ]
    )

    # Top-level function names defined in the hand-maintained JS prelude.
    text = PRELUDE_JS.read_text(encoding="utf-8") if PRELUDE_JS.exists() else ""
    for m in re.finditer(
        r"(?:^|\n)\s*(?:function\s+|var\s+)?([A-Za-z_]\w*)\s*=?\s*function", text
    ):
        symbols.add(m.group(1))
    for m in re.finditer(r"(?:^|\n)\s*function\s+([A-Za-z_]\w*)\s*\(", text):
        symbols.add(m.group(1))

    return sorted(s for s in symbols if not s.startswith("__"))


def main():
    if not SCHEMA.exists():
        print(
            "[sdk] %s not found; run --dump-api-schema first" % SCHEMA, file=sys.stderr
        )
        return 1

    commands = json.loads(SCHEMA.read_text(encoding="utf-8"))
    commands = drop_namespace_collisions(commands)
    commands.sort(key=lambda c: c["name"])

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_JS.write_bytes(emit_js(commands).encode("utf-8"))
    OUT_LUA.write_bytes(emit_lua(commands).encode("utf-8"))

    symbols = collect_symbols(commands)
    OUT_SYMBOLS.write_bytes((json.dumps(symbols, indent=2) + "\n").encode("utf-8"))

    print(
        "[sdk] wrote %s, %s, %s (%d commands, %d symbols)"
        % (OUT_JS.name, OUT_LUA.name, OUT_SYMBOLS.name, len(commands), len(symbols)),
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
