#include <QMap>
#include <QFile>
#include <QFont>
#include <QLabel>
#include <QTimer>
#include <QColor>
#include <QtMath>
#include <QwtPlot>
#include <QWidget>
#include <QVector>
#include <QObject>
#include <QwtDial>
#include <QPainter>
#include <QVariant>
#include <QwtLegend>
#include <QComboBox>
#include <QDateTime>
#include <QwtThermo>
#include <QJsonArray>
#include <QwtCompass>
#include <QTcpSocket>
#include <QTcpServer>
#include <QByteArray>
#include <QVBoxLayout>
#include <QGridLayout>
#include <QScrollArea>
#include <QMouseEvent>
#include <QWheelEvent>
#include <QJsonObject>
#include <QHBoxLayout>
#include <QMessageBox>
#include <QwtPlotCurve>
#include <QResizeEvent>
#include <QHostAddress>
#include <QApplication>
#include <QElapsedTimer>
#include <QJsonDocument>
#include <QwtDialNeedle>
#include <QPlainTextEdit>
#include <QwtScaleEngine>
#include <QQuickPaintedItem>
#include <QRegularExpression>
#include <QNetworkAccessManager>
